## Types of Recommender Systems

* 1. Content based
* 2. Collaborative filtering 
* 3. Hybrid

In [2]:
import numpy as np
import pandas as pd

In [3]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [4]:
movies.head(1)

      budget  ... vote_count
0  237000000  ...      11800

[1 rows x 20 columns]

In [5]:
credits.head(1)

   movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...

[1 rows x 4 columns]

## Both dataset are for same move so we can marge both of them :- base of Movie_id or we can title

In [6]:
# marge data with title
Movies = movies.merge(credits,on='title')

In [7]:
Movies.head(1)

      budget  ...                                               crew
0  237000000  ...  [{"credit_id": "52fe48009251416c750aca23", "de...

[1 rows x 23 columns]

## Colum we are using 
* 1.  Genres
* 2. id
* 3. keywords
* 4. title
* 5. Overview
* 6. cast
* 7. crew

## Column we are going to remove 
* 1. budget
* 2. Homepage
* 3. popularity
* 4. Production_compaies
* 5. Production_countries
* 6. release_date
* 7. revenue
* 8. runtime
* 9. spoken_language
* 10. status
* 11. tagline
* 12. vote_average
* 13. vote_count
* 14. movie_id

In [8]:
movies = Movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [9]:
movies.head()

   movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 7 columns]

In [10]:
# creating a new column with overview , genres, keywords , cast , crew

In [11]:
# finding new null values 
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [12]:
# removing null values row 
movies.dropna(inplace = True)

C:\Users\USER\AppData\Local\Temp\ipykernel_17696\3788524121.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.dropna(inplace = True)

In [13]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [14]:
# finding duplicated row
movies.duplicated().sum()

0

In [15]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [16]:
# getting array in genres

In [17]:
import ast
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [18]:
movies['genres']=movies['genres'].apply(convert)

C:\Users\USER\AppData\Local\Temp\ipykernel_17696\46431500.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres']=movies['genres'].apply(convert)

In [19]:
movies.head()

   movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 7 columns]

In [20]:
movies['keywords'] = movies['keywords'].apply(convert)

C:\Users\USER\AppData\Local\Temp\ipykernel_17696\3328512696.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords'] = movies['keywords'].apply(convert)

In [21]:
movies['cast'] = movies['cast'].apply(convert)

C:\Users\USER\AppData\Local\Temp\ipykernel_17696\2217188125.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast'] = movies['cast'].apply(convert)

In [22]:
movies.head()

   movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 7 columns]

In [23]:
def convert3(cast_list):
    return (cast_list + [None]*3)[:3]

In [24]:
movies['cast'] = movies['cast'].apply(convert3)

C:\Users\USER\AppData\Local\Temp\ipykernel_17696\3593664571.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast'] = movies['cast'].apply(convert3)

In [25]:
movies.head()

   movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 7 columns]

In [26]:

def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] =='Director':
          L.append(i['name'])
          break
    return L

In [27]:
movies['crew'] = movies['crew'].apply(fetch_director)

C:\Users\USER\AppData\Local\Temp\ipykernel_17696\2884021428.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew'] = movies['crew'].apply(fetch_director)

In [28]:
movies.head()

   movie_id  ...                 crew
0     19995  ...      [James Cameron]
1       285  ...     [Gore Verbinski]
2    206647  ...         [Sam Mendes]
3     49026  ...  [Christopher Nolan]
4     49529  ...     [Andrew Stanton]

[5 rows x 7 columns]

In [29]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [30]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

C:\Users\USER\AppData\Local\Temp\ipykernel_17696\3942134491.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [31]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

C:\Users\USER\AppData\Local\Temp\ipykernel_17696\2275653948.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

In [32]:
movies['Keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

C:\Users\USER\AppData\Local\Temp\ipykernel_17696\1730154281.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['Keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

In [33]:
movies['cast'] = movies['cast'].apply(
    lambda x: [i.replace(" ", "") for i in x if isinstance(i, str)] if isinstance(x, list) else []
)

C:\Users\USER\AppData\Local\Temp\ipykernel_17696\97568058.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast'] = movies['cast'].apply(

In [34]:
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

C:\Users\USER\AppData\Local\Temp\ipykernel_17696\4142431194.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [35]:
movies.head()

   movie_id  ...                                           Keywords
0     19995  ...  [cultureclash, future, spacewar, spacecolony, ...
1       285  ...  [ocean, drugabuse, exoticisland, eastindiatrad...
2    206647  ...  [spy, basedonnovel, secretagent, sequel, mi6, ...
3     49026  ...  [dccomics, crimefighter, terrorist, secretiden...
4     49529  ...  [basedonnovel, mars, medallion, spacetravel, p...

[5 rows x 8 columns]

In [36]:

movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

C:\Users\USER\AppData\Local\Temp\ipykernel_17696\3770452025.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [37]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew','Keywords'])

In [38]:
new.head()

   movie_id  ...                                               tags
0     19995  ...  [In, the, 22nd, century,, a, paraplegic, Marin...
1       285  ...  [Captain, Barbossa,, long, believed, to, be, d...
2    206647  ...  [A, cryptic, message, from, Bond’s, past, send...
3     49026  ...  [Following, the, death, of, District, Attorney...
4     49529  ...  [John, Carter, is, a, war-weary,, former, mili...

[5 rows x 3 columns]

In [39]:
new['tag'] = new['tags'].apply(lambda x:" ".join(x))

In [40]:
new.head()

   movie_id  ...                                                tag
0     19995  ...  In the 22nd century, a paraplegic Marine is di...
1       285  ...  Captain Barbossa, long believed to be dead, ha...
2    206647  ...  A cryptic message from Bond’s past sends him o...
3     49026  ...  Following the death of District Attorney Harve...
4     49529  ...  John Carter is a war-weary, former military ca...

[5 rows x 4 columns]

In [41]:
new_df = new.drop(columns = ['tags'])

In [42]:
new_df

      movie_id  ...                                                tag
0        19995  ...  In the 22nd century, a paraplegic Marine is di...
1          285  ...  Captain Barbossa, long believed to be dead, ha...
2       206647  ...  A cryptic message from Bond’s past sends him o...
3        49026  ...  Following the death of District Attorney Harve...
4        49529  ...  John Carter is a war-weary, former military ca...
...        ...  ...                                                ...
4804      9367  ...  El Mariachi just wants to play his guitar and ...
4805     72766  ...  A newlywed couple's honeymoon is upended by th...
4806    231617  ...  "Signed, Sealed, Delivered" introduces a dedic...
4807    126186  ...  When ambitious New York attorney Sam is sent t...
4808     25975  ...  Ever since the second grade when he first saw ...

[4806 rows x 3 columns]

In [43]:
new_df['tag']=new_df['tag'].apply(lambda x:x.lower())

In [44]:
import nltk

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [45]:
def stem(text):
    y =[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [46]:
new_df['tag'] =new_df['tag'].apply(stem)

In [47]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features =5000, stop_words ='english')

In [48]:
cv.fit_transform(new_df['tag']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [49]:
cv.fit_transform(new_df['tag']).toarray().shape

(4806, 5000)

In [50]:
vectors = cv.fit_transform(new_df['tag']).toarray()

In [51]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [52]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [53]:
from sklearn.metrics.pairwise import cosine_similarity

In [55]:
cosine_similarity(vectors).shape

(4806, 4806)

In [56]:
similarity = cosine_similarity(vectors)

In [58]:
similarity[0]

array([1.        , 0.07156563, 0.05249442, ..., 0.04845016, 0.        ,
       0.        ])

In [65]:
def recommned(movies):
    movies_index = new_df[new_df['title'] == movies].index[0]
    distances = similarity[movies_index]
    movies_list  = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [66]:
recommned('Avatar')

Aliens
Silent Running
Mission to Mars
Moonraker
Alien³

In [67]:
recommned('Batman Begins')

The Dark Knight
Batman
Batman
The Dark Knight Rises
Batman & Robin