## Data Analysis Process

1. Asking Questions
2. Data Wrangling<br>
    a. Gathering Data
        - i. CSV files
        - ii. APIs
        - iii. Web Scraping
        - iv. Databases
    b. Assessing Data<br>
    c. Cleaning Data
3. Exploratory Data Analysis
4. Drawing Conclusion
5. Comunicating Results

## 1b. Data Accessing

In this step , the data is to be understood more deeply. Before implementing methods to clean it , you will definitely need to have a better idea about what the data is about .

# Types of Unclean Data
There are 2 kinds of unclean data 

* `Dirty Data (data with Quality issues)`: Dirty data, also known as low quality data . Low quality data has content issues .

   * Duplicated data
   * Missing data 
   * Corrupt data
   * Inaccurate Data

* `Messy Data( Data With tidiness issues)`: Messy data , also known as untidy data. Untidy data has structural issues . Tidy data has the following properties:
    * Each variable forms a column
    * Each observation forms a row 
    * Each observational unit forms a table

In [1]:
import pandas as pd
import numpy as np

In [2]:
patients = pd.read_csv('patients.csv')
treatments = pd.read_csv('treatments.csv')
adverse_reactions = pd.read_csv('adverse_reactions.csv')
treatments_cut = pd.read_csv('treatments_cut.csv')

In [3]:
patients.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

# What Is the goal of this analysis
* Are we analyzing general health trends?
* Are we trying to identify patients at risk based on BMI?
* Is this  for reporting , diagnosis support or outreach?

# 🧑‍🤝‍🧑 Who is the audience?
* Doctors or healthcare providers ?
* Insurance Companies?
* Public health officials ?
* A data science team building predictive medels?✅

# What does each row represent ?
* Each row appears to represent a unique patient record, including personal and health information.

# What do the columns means?
* `patient_id` :- Unique identifier for each patient
* `assigned_sex` :- Gender assigned at registration(may differ from biological)
* `given_name , surname` :- Patient's full name
* `address ,city,state,zip_code,country` :- Location info
* `contact` :- Email/Phone - some messay data here(merged)
* `birthdata` :- Patient's dat pf birth
* `weight(lbs)` :- Body weight
* `height(inches)` :- Body height
* `Bmi`:- Body Mass Index(Calculated from height and weight)

# About the dataset that  is important 

* Who collected this  data , and when ?
* Are any fields calculated (e.g.,`bmi`) or manually entered?
* Are names and contact info real or anonymized?

# 🔍 2. Ask Descriptive Questions (What happened?)
These help you summarize the dataset:

In [4]:
# How many rows and columns are there
patients.shape

(503, 14)

In [60]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       491 non-null    object
 5   city          491 non-null    object
 6   state         491 non-null    object
 7   zip_code      491 non-null    float64
 8   country       491 non-null    object
 9   contact       491 non-null    object
 10  birthdate     503 non-null    datetime64[ns]
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
 14  age           503 non-null    int64
dtypes: datetime64[ns](1), float64(3), int64(3), object(8)
memory usage: 59.1+ KB

In [61]:
patients.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi,age
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,1976-07-10,121.7,66,19.6,48
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,1967-04-03,118.8,66,19.2,58
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,1980-02-19,177.8,71,24.8,45
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,1951-07-26,220.9,70,31.7,73
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,1928-02-18,192.3,27,26.1,97

In [62]:
patients.tail()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi,age
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,ME,3852.0,United States,207-477-0579MustafaLindstrom@jourrapide.com,1959-04-10,181.1,72,24.6,66
499,500,male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,AZ,86341.0,United States,928-284-4492RumanBisliev@gustr.com,1948-03-26,239.6,70,34.4,77
500,501,female,Jinke,de Keizer,649 Nutter Street,Overland Park,MO,64110.0,United States,816-223-6007JinkedeKeizer@teleworm.us,1971-01-13,171.2,67,26.8,54
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,WA,98109.0,United States,ChidaluOnyekaozulu@jourrapide.com1 360 443 2060,1952-02-13,176.9,67,27.7,73
502,503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324.0,United States,PatrickGersten@rhyta.com402-848-4923,1954-05-03,138.2,71,19.3,70

In [63]:
patients.sample()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi,age
191,192,female,Fanette,Fournier,602 Tator Patch Road,Chicago,Illinois,60607.0,United States,FanetteFournier@einrot.com+1 (312) 864-5737,1938-10-24,112.6,60,22.0,86

In [6]:
# Are there missing values?
patients.isnull().sum()

patient_id       0
assigned_sex     0
given_name       0
surname          0
address         12
city            12
state           12
zip_code        12
country         12
contact         12
birthdate        0
weight           0
height           0
bmi              0
dtype: int64

In [7]:
# What are the data types?
patients.dtypes

patient_id        int64
assigned_sex     object
given_name       object
surname          object
address          object
city             object
state            object
zip_code        float64
country          object
contact          object
birthdate        object
weight          float64
height            int64
bmi             float64
dtype: object

In [65]:
patients.duplicated().sum()

0

In [67]:
patients[patients['address'].duplicated()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi,age
29,30,male,Jake,Jakobsen,648 Old Dear Lane,Port Jervis,New York,12771.0,United States,JakobCJakobsen@einrot.com+1 (845) 858-7707,1985-08-01,155.8,67,24.4,39
219,220,male,Mỹ,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,1978-04-09,237.8,69,35.1,47
229,230,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1975-01-01,180.0,72,24.4,50
230,231,female,Elisabeth,Knudsen,NaN,NaN,NaN,NaN,NaN,NaN,1976-09-23,165.9,63,29.4,48
234,235,female,Martina,Tománková,NaN,NaN,NaN,NaN,NaN,NaN,1936-04-07,199.5,65,33.2,89
237,238,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1975-01-01,180.0,72,24.4,50
242,243,male,John,O'Brian,NaN,NaN,NaN,NaN,NaN,NaN,1957-02-25,205.3,74,26.4,68
244,245,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1975-01-01,180.0,72,24.4,50
249,250,male,Benjamin,Mehler,NaN,NaN,NaN,NaN,NaN,NaN,1951-10-30,146.5,69,21.6,73
251,252,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1975-01-01,180.0,72,24.4,50
257,258,male,Jin,Kung,NaN,NaN,NaN,NaN,NaN,NaN,1995-05-17,231.7,69,34.2,29
264,265,female,Wafiyyah,Asfour,NaN,NaN,NaN,NaN,NaN,NaN,1989-11-03,158.6,63,28.1,35
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,1937-10-09,175.2,61,33.1,87
277,278,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1975-01-01,180.0,72,24.4,50
278,279,female,Generosa,Cabán,NaN,NaN,NaN,NaN,NaN,NaN,1962-12-16,124.3,69,18.4,62
282,283,female,Sandy,Taylor,2476 Fulton Street,Rainelle,WV,25962.0,United States,304-438-2648SandraCTaylor@dayrep.com,1960-10-23,206.1,64,35.4,64
286,287,male,Lewis,Webb,NaN,NaN,NaN,NaN,NaN,NaN,1979-04-01,155.3,68,23.6,46
296,297,female,Chỉ,Lâm,NaN,NaN,NaN,NaN,NaN,NaN,1990-05-14,181.1,63,32.1,34
502,503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324.0,United States,PatrickGersten@rhyta.com402-848-4923,1954-05-03,138.2,71,19.3,70

# which column in which type 
* Categorical :- assigned_sex, city ,state, country
* Numeric:-patient_id,weight, height,bmi
* Data:- birthdate(converted to data end time )
* mix :- given_name,surname

In [ ]:
# Range of values in numerical colums 
# range  only  find in numerical column it is not use for categorical columns 
patients.describe()

       patient_id      zip_code      weight      height         bmi
count  503.000000    491.000000  503.000000  503.000000  503.000000
mean   252.000000  49084.118126  173.434990   66.634195   27.483897
std    145.347859  30265.807442   33.916741    4.411297    5.276438
min      1.000000   1002.000000   48.800000   27.000000   17.100000
25%    126.500000  21920.500000  149.300000   63.000000   23.300000
50%    252.000000  48057.000000  175.300000   67.000000   27.200000
75%    377.500000  75679.000000  199.500000   70.000000   31.750000
max    503.000000  99701.000000  255.900000   79.000000   37.700000

In [13]:
patients[patients['weight']==patients['weight'].max()]
# what this is line is saying :- find the patient with maximum weight in patients list and take it for me and all details about the patient

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
485,486,male,Trifon,Izmailov,3697 Drainer Avenue,Fort Walton Beach,FL,32548.0,United States,TrifonIzmailov@fleckens.hu1 850 659 0417,2/15/1973,255.9,74,32.9

In [ ]:
# 2️⃣ See patients with height below 30 inches (very short, possibly incorrect):
patients[patients['height'] >30]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
5,6,male,Rafael,Costa,1140 Willis Avenue,Daytona Beach,Florida,32114.0,United States,386-334-5237RafaelCardosoCosta@gustr.com,8/31/1931,183.9,70,26.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,ME,3852.0,United States,207-477-0579MustafaLindstrom@jourrapide.com,4/10/1959,181.1,72,24.6
499,500,male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,AZ,86341.0,United States,928-284-4492RumanBisliev@gustr.com,3/26/1948,239.6,70,34.4
500,501,female,Jinke,de Keizer,649 Nutter Street,Overland Park,MO,64110.0,United States,816-223-6007JinkedeKeizer@teleworm.us,1/13/1971,171.2,67,26.8
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,WA,98109.0,United States,ChidaluOnyekaozulu@jourrapide.com1 360 443 2060,2/13/1952,176.9,67,27.7
502,503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324.0,United States,PatrickGersten@rhyta.com402-848-4923,5/3/1954,138.2,71,19.3

In [18]:
# 3️⃣ See all patients with BMI above 35 (could be considered obese):
patients[patients['bmi'] > 35]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
10,11,female,Sandy,Gunnarsson,87 Wood Duck Drive,Rudyard,MI,49780.0,United States,906-478-8949SandyGunnarsson@dayrep.com,7/16/1974,199.3,62,36.4
13,14,female,Anenechi,Chidi,826 Broad Street,Birmingham,AL,35203.0,United States,AnenechiChidi@armyspy.com+1 (205) 417-8095,3/7/1961,228.4,67,35.8
23,24,male,Lovre,Galić,4941 Marion Drive,Winter Haven,Florida,33830.0,United States,LovreGalic@gustr.com1 813 355 9476,5/26/1960,222.9,66,36.0
35,36,female,Kamila,Pecinová,3558 Longview Avenue,New York,New York,10004.0,United States,718-501-0503KamilaPecinova@dayrep.com,12/23/1985,198.9,62,36.4
42,43,female,Mizuki,Iwata,3434 Holt Street,West Palm Beach,FL,33409.0,United States,MizukiIwata@gustr.com561-357-0702,6/30/1927,199.1,61,37.6
52,53,female,Brianna,Lansell,1389 Nutters Barn Lane,Urbandale,IA,50322.0,United States,515-727-9324BriannaLansell@fleckens.hu,12/4/1950,202.0,62,36.9
61,62,male,Alan,Milne,707 Gateway Avenue,Bakersfield,California,93301.0,United States,AlanMilne@dayrep.com1 661 779 6795,4/29/1962,244.9,69,36.2
72,73,male,Søren,Frederiksen,4852 Rose Avenue,Metairie,LA,70001.0,United States,SrenFrederiksen@armyspy.com504-289-1386,2/12/1931,214.5,65,35.7
91,92,female,Caroline,Shuler,1403 Clousson Road,Houston,TX,77002.0,United States,CarolineTShuler@jourrapide.com713-230-1739,3/8/1949,218.7,66,35.3
96,97,female,Nasim,Salib,3161 Fantages Way,Presque Isle,ME,4769.0,United States,207-768-0477NasimSumaiyaSalib@einrot.com,7/30/1971,211.4,65,35.2
104,105,female,Yasmin,Silva,108 Griffin Street,Phoenix,AZ,85012.0,United States,YasminAlmeidaSilva@einrot.com1 602 265 7408,7/24/1927,200.6,62,36.7
113,114,female,Svanhvít,Guðjónsdóttir,2641 Michael Street,Houston,TX,77074.0,United States,SvanhvitGujonsdottir@cuvox.de1 713 779 6516,7/23/1931,204.2,63,36.2
125,126,female,Seweryna,Czerwinska,36 Heather Sees Way,Tulsa,OK,74119.0,United States,918-714-7543SewerynaCzerwinska@jourrapide.com,6/30/1982,203.5,63,36.0
130,131,male,Albert,Wolfe,3710 Jerry Dove Drive,North Charleston,SC,29420.0,United States,843-494-0313AlbertRWolfe@jourrapide.com,6/16/1939,217.8,65,36.2
131,132,female,Sandra,Taylor,2476 Fulton Street,Rainelle,WV,25962.0,United States,304-438-2648SandraCTaylor@dayrep.com,10/23/1960,206.1,64,35.4
151,152,female,Satsita,Batukayev,2813 Frederick Street,Citrus Heights,California,95610.0,United States,916-224-7868SatsitaBatukayev@teleworm.us,2/17/1953,219.6,66,35.4
157,158,female,Ellen,Luman,4643 Reeves Street,Chilton,WI,53014.0,United States,EllenRLuman@einrot.com920-849-0384,2/26/1951,184.6,60,36.0
162,163,female,Sarina,Tabata,4646 Highland View Drive,Sacramento,CA,95814.0,United States,SarinaTabata@teleworm.us916-555-7247,4/21/1967,201.7,63,35.7
177,178,female,Monika,Lončar,377 Norman Street,Los Angeles,CA,90014.0,United States,323-327-4721MonikaLoncar@rhyta.com,7/19/1927,203.7,63,36.1
203,204,female,Mùi,Lương,1778 Rodney Street,Harvester,MO,63301.0,United States,636-442-6946LuongHongMui@einrot.com,2/29/1956,192.7,60,37.6
219,220,male,Mỹ,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,4/9/1978,237.8,69,35.1
223,224,female,Virginia,Boyles,945 Maple Avenue,Downey,ID,83234.0,United States,VirginiaABoyles@gustr.com1 208 897 3897,9/22/1939,202.4,63,35.8
227,228,female,Laura,Ehrlichmann,1829 Bungalow Road,Omaha,NE,68124.0,United States,402-938-2157LauraEhrlichmann@einrot.com,1/3/1942,187.9,60,36.7
236,237,female,Fatimah,Kinfe,2640 Sweetwood Drive,Aurora,CO,80010.0,United States,303-360-3627FatimahKinfe@fleckens.hu,1/21/1981,199.8,62,36.5
240,241,female,Marphisa,Compagnon,3391 Marcus Street,Huntsville,AL,35806.0,United States,MarphisaCompagnon@cuvox.de+1 (256) 615-5522,3/9/1967,198.0,63,35.1
245,246,female,Isabelle,Nash,932 Memory Lane,Rockford,Illinois,61101.0,United States,815-979-8782IsabelleNash@einrot.com,2/3/1986,206.1,62,37.7
246,247,female,Meya,Sjöberg,1233 Liberty Avenue,Santa Ana,California,92704.0,United States,714-431-2746MeyaSjoberg@cuvox.de,5/15/1968,232.1,66,37.5
250,251,female,Mee,Chung,3084 Blue Spruce Lane,Dundalk,MD,21222.0,United States,410-284-8935MeeChung@teleworm.us,10/27/1932,206.1,64,35.4
255,256,female,Mette,Sandgreen,2324 Benson Street,Elk Lake,WI,54739.0,United States,MetteSandgreen@gustr.com715-231-3508,5/13/1938,187.1,60,36.5
266,267,female,Johanna,Dreher,3857 Straford Park,Whitesburg,KY,41858.0,United States,JohannaDreher@superrito.com1 606 632 4327,10/6/1948,187.0,61,35.3
279,280,female,Hanna-Mari,Filatov,2127 Columbia Mine Road,Riverton,WV,26814.0,United States,304-567-9723Hanna-MariFilatov@fleckens.hu,1/5/1967,200.8,62,36.7
282,283,female,Sandy,Taylor,2476 Fulton Street,Rainelle,WV,25962.0,United States,304-438-2648SandraCTaylor@dayrep.com,10/23/1960,206.1,64,35.4
283,284,male,Nwachukwu,Nebeolisa,2873 John Calvin Drive,Chicago,IL,60605.0,United States,NwachukwuNebeolisa@cuvox.de+1 (708) 845-2053,3/10/1986,245.5,68,37.3
322,323,male,Mười,Liễu,4346 Sussex Court,Chilton,TX,76632.0,United States,254-546-2728LieuThanhMuoi@teleworm.us,7/27/1974,218.5,66,35.3
332,333,male,Abel,Efrem,2333 Hidden Pond Road,Old Hickory,TN,37138.0,United States,AbelEfrem@fleckens.hu1 615 755 8235,2/15/1971,224.0,67,35.1
339,340,male,Pavel,Filípek,3094 Oral Lake Road,Apple Valley,MN,55124.0,United States,PavelFilipek@rhyta.com1 952 431 5166,8/18/1977,229.0,67,35.9
352,353,male,Marek,﻿Dvořák,633 Better Street,Savannah,GA,31401.0,United States,912-988-6655MarekDvorak@gustr.com,12/19/1966,227.7,67,35.7
355,356,female,Chiho,Higa,4500 Myra Street,Providence,RI,2905.0,United States,ChihoHiga@teleworm.us401-456-2797,5/25/1935,182.6,59,36.9
367,368,female,Ava,Fisher,4386 Camden Street,Sparks,NV,89431.0,United States,775-358-9076AvaFisher@rhyta.com,3/29/1928,191.0,60,37.3
376,377,female,Ivona,Jakšić,1051 Bassell Avenue,Wichita,AR,67202.0,United States,IvonaJaksic@einrot.com+1 (501) 636-4058,9/5/1935,200.8,62,36.7
403,404,male,Robert,Maslov,2356 Myra Street,Providence,RI,2908.0,United States,RobertMaslov@fleckens.hu401-535-2675,7/2/1932,219.1,65,36.5
431,432,female,Manuela,Cindrić,4120 Thompson Drive,Dublin,California,94568.0,United States,510-376-3772ManuelaCindric@gustr.com,12/1/1942,219.9,64,37.7
443,444,female,Kajsa,Eidem,1953 Rhapsody Street,Ocala,Florida,34471.0,United States,KajsaEidem@superrito.com352-362-5392,4/26/1964,191.0,60,37.3
469,470,male,Harley,Tucker,1067 Ray Court,Wilmington,NC,28412.0,United States,910-264-6229HarleyTucker@fleckens.hu,9/21/1965,220.4,66,35.6
479,480,male,Tapa,Arsanukayev,4720 Gordon Street,Ontario,California,91762.0,United States,TapaArsanukayev@dayrep.com1 909 458 2515,9/15/1955,220.0,65,36.6
482,483,male,Diogo,Souza,4033 White Avenue,Corpus Christi,TX,78401.0,United States,361-693-4960DiogoBarrosSouza@jourrapide.com,3/3/1945,220.0,65,36.6

In [19]:
# 4️⃣ See patients with ZIP code less than 10000 (unusual ZIPs):
patients[patients['zip_code'] < 10000]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
20,21,female,Sofia,Karlsen,2931 Romano Street,Whitman,MA,2382.0,United States,SofiaTKarlsen@teleworm.us1 781 447 1763,9/24/1934,153.1,66,24.7
34,35,female,Mariana,Souza,577 Chipmunk Lane,Orrington,ME,4474.0,United States,207-825-8634MarianaGomesSouza@superrito.com,3/6/1948,152.9,63,27.1
38,39,female,Genet,Fesahaye,4649 Joanne Lane,Westborough,MA,1581.0,United States,GenetFesahaye@armyspy.com1 978 460 9060,1/11/1954,111.8,67,17.5
39,40,female,Ganimete,Ščančar,4105 Ferguson Street,Walpole,MA,2081.0,United States,508-454-2027GanimeteScancar@cuvox.de,10/25/1947,191.6,67,30.0
44,45,female,Blanka,Jurković,3165 Upton Avenue,Waterville,ME,4901.0,United States,BlankaJurkovic@superrito.com1 207 861 4587,1/26/1923,129.8,66,20.9
53,54,male,Kwemtochukwu,Ogochukwu,2172 Lynn Street,Franklin,MA,2038.0,United States,617-317-5055KwemtochukwuOgochukwu@einrot.com,6/30/1976,150.5,72,20.4
54,55,female,Louise,Johnson,4984 Hampton Meadows,Burlington,MA,1803.0,United States,LouiseJohnson@rhyta.com978-407-1874,3/1/1931,141.0,62,25.8
62,63,female,Firenze,Fodor,1786 Gerald L. Bates Drive,Belmont,MA,2178.0,United States,617-883-5967FodorFirenze@dayrep.com,4/1/1943,131.1,60,25.6
67,68,male,Nebechi,Ekechukwu,2418 Smith Street,Marlboro,MA,1752.0,United States,NebechiEkechukwu@teleworm.us508-804-4850,1/11/1945,154.9,64,26.6
71,72,male,Leuco,Miranda,90 Meadow View Drive,Hartford,CT,6103.0,United States,860-515-0122LeucoMirandaNieto@teleworm.us,2/2/1976,184.8,72,25.1
73,74,female,Žarka,Rap,2661 Russell Street,Foxboro,MA,2035.0,United States,978-969-6753ZarkaRap@superrito.com,12/28/1995,139.3,68,21.2
78,79,female,Fauna,Bilodeau,4104 Kennedy Court,Mansfield,MA,2048.0,United States,FaunaBilodeau@teleworm.us1 774 263 5317,7/2/1979,193.4,69,28.6
92,93,male,Michael,Smith,666 Whiteman Street,Mount Holly,NJ,8060.0,United States,609-914-8473MichaelSmith@armyspy.com,9/17/1977,160.6,67,25.2
96,97,female,Nasim,Salib,3161 Fantages Way,Presque Isle,ME,4769.0,United States,207-768-0477NasimSumaiyaSalib@einrot.com,7/30/1971,211.4,65,35.2
124,125,male,Ming,Hsu,2945 Ferguson Street,Quincy,MA,2169.0,United States,MingHsu@armyspy.com+1 (508) 526-3432,11/4/1960,215.6,69,31.8
126,127,male,Mads,Nielsen,1493 Randolph Street,Boston,MA,2210.0,United States,MadsANielsen@jourrapide.com508-739-5632,5/19/1942,137.1,68,20.8
167,168,female,Melisa,Mata,2775 Single Street,Bedford,MA,1730.0,United States,781-604-1901MelisaMataSantacruz@rhyta.com,12/15/1941,209.7,65,34.9
176,177,female,Makda,Abraham,4093 Smith Street,Lowell,MA,1852.0,United States,MakdaAbraham@einrot.com1 508 857 0477,6/24/1979,145.2,65,24.2
182,183,male,Kaodilinakachukwu,Nnonso,3261 Desert Broom Court,Jersey City,NJ,7304.0,United States,201-739-3931KaodilinakachukwuNnonso@gustr.com,11/9/1963,230.3,69,34.0
186,187,female,Jane,Citizen,2866 Myra Street,Providence,RI,2908.0,United States,JaneCitizen@cuvox.de+1 (401) 485-6384,9/27/1974,143.0,65,23.8
193,194,male,Borna,Šlezinger,3073 Bedford Street,West Haven,CT,6516.0,United States,BornaSlezinger@cuvox.de203-933-3979,3/21/1987,203.9,69,30.1
194,195,male,Urso,Aranda,1330 Lincoln Street,Hopewell Mercer,NJ,8525.0,United States,609-466-3275UrsoArandaSanchez@rhyta.com,7/3/1999,163.7,70,23.5
200,201,male,Kifle,Mustafa,4535 Prospect Street,Pennsauken,NJ,8110.0,United States,856-655-5415KifleMustafa@gustr.com,10/9/1965,186.1,69,27.5
201,202,male,Pirro,Galvez,2831 Milford Street,Exeter,NH,3833.0,United States,PirroGalvezPaz@armyspy.com1 603 773 2333,2/25/1971,172.5,73,22.8
214,215,female,Gabriela,Michalčíková,383 Marion Street,Hartford,VT,5047.0,United States,GabrielaMichalcikova@rhyta.com+1 (802) 952-6490,10/8/1964,126.9,65,21.1
224,225,female,Veronika,Jindrová,3641 Selah Way,Brattleboro,VT,5301.0,United States,802-614-0812VeronikaJindrova@jourrapide.com,1/15/1981,171.4,62,31.3
252,253,male,Juan,Pérez,2549 Pearlman Avenue,Bedford,MA,1730.0,United States,978-243-8596JuanPerez@teleworm.us,10/1/1991,224.2,70,32.2
261,262,male,Jeremy,Montagu,4988 Lynn Street,Boston,MA,2110.0,United States,JeremyMontagu@teleworm.us617-297-0387,6/23/1982,192.7,74,24.7
284,285,male,Nilton,Quintanilla,4038 Farland Street,Walpole,MA,2081.0,United States,774-219-3140NiltonQuintanillaAlmonte@rhyta.com,2/9/1980,186.3,75,23.3
290,291,female,Una,Traustadóttir,1027 Tenmile Road,Bedford,MA,1730.0,United States,781-739-0244UnaTraustadottir@armyspy.com,2/1/1930,152.3,59,30.8
294,295,female,Annie,Allen,3634 Lyon Avenue,Cambridge,MA,2142.0,United States,AnnieJAllen@superrito.com1 508 921 6327,3/31/1926,159.7,60,31.2
314,315,male,Renzo,Lucchese,4145 Fairfax Drive,Branchburg,NJ,8876.0,United States,908-884-4247RenzoLucchese@dayrep.com,2/5/1970,212.1,69,31.3
316,317,female,Chân,Bùi,115 Frank Avenue,Amherst,MA,1002.0,United States,413-259-3637BuiQuynhChan@fleckens.hu,10/11/1932,162.1,61,30.6
327,328,male,Torfi,Írisarson,1463 Beechwood Avenue,Belleville,NJ,7109.0,United States,908-871-7009TorfiIrisarson@jourrapide.com,10/3/1977,214.7,68,32.6
342,343,female,Mathilde,Nørgaard,846 Copperhead Road,Hartford,CT,6182.0,United States,MathildeDNrgaard@superrito.com1 860 618 4560,1/21/1985,127.2,61,24.0
343,344,female,Emy,Markus,288 Colony Street,Stamford,CT,6901.0,United States,203-251-3573EmyMarkus@armyspy.com,1/30/1999,140.6,65,23.4
354,355,female,Vivian,House,4932 Goldleaf Lane,Newark,NJ,7102.0,United States,201-586-2848VivianRHouse@dayrep.com,8/13/1936,130.2,62,23.8
355,356,female,Chiho,Higa,4500 Myra Street,Providence,RI,2905.0,United States,ChihoHiga@teleworm.us401-456-2797,5/25/1935,182.6,59,36.9
358,359,female,Amalie,Christensen,3077 Colony Street,Meriden,CT,6450.0,United States,AmalieJChristensen@einrot.com1 203 235 1076,10/1/1941,160.8,63,28.5
368,369,male,Corey,Nicholls,3427 Gerald L. Bates Drive,Boston,MA,2110.0,United States,CoreyNicholls@jourrapide.com1 617 830 7216,4/25/1989,165.0,74,21.2
370,371,male,Olof,Holm,288 Smith Street,Taunton,MA,2780.0,United States,508-821-2421OlofHolm@gustr.com,4/7/1999,214.1,70,30.7
371,372,female,Asya,Musliyevich,1763 Williams Mine Road,Weehawken,NJ,7087.0,United States,AsyaMusliyevich@armyspy.com+1 (908) 287-7099,7/15/1995,156.0,63,27.6
380,381,female,Silje,Kristiansen,4992 Moonlight Drive,Pleasantville,NJ,8232.0,United States,SiljeAKristiansen@dayrep.com609-641-2070,2/7/1996,162.4,64,27.9
403,404,male,Robert,Maslov,2356 Myra Street,Providence,RI,2908.0,United States,RobertMaslov@fleckens.hu401-535-2675,7/2/1932,219.1,65,36.5
424,425,female,Krystiana,Kozłowska,2935 Diamond Cove,Providence,RI,2906.0,United States,KrystianaKozlowska@cuvox.de+1 (401) 419-2975,11/8/1921,123.6,63,21.9
425,426,female,Taylah,Mobourne,995 Beechwood Avenue,Weehawken,NJ,7087.0,United States,908-751-4255TaylahMobourne@rhyta.com,7/4/1961,188.5,67,29.5
473,474,female,Kate,Wilkinson,664 Lyon Avenue,South Boston,MA,2127.0,United States,KateWilkinson@armyspy.com1 508 905 2371,7/18/1998,175.3,65,29.2
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,ME,3852.0,United States,207-477-0579MustafaLindstrom@jourrapide.com,4/10/1959,181.1,72,24.6

In [22]:
# 5️⃣ Get all patients between 25th and 75th percentile BMI (normal range):
patients[(patients['bmi'] >=23.3) & (patients['bmi']<=31.75)]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1
5,6,male,Rafael,Costa,1140 Willis Avenue,Daytona Beach,Florida,32114.0,United States,386-334-5237RafaelCardosoCosta@gustr.com,8/31/1931,183.9,70,26.4
6,7,female,Mary,Adams,3145 Sheila Lane,Burbank,NV,84728.0,United States,775-533-5933MaryBAdams@einrot.com,11/19/1969,146.3,65,24.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,male,Hajime,Tsukada,4111 Thunder Road,San Mateo,CA,94403.0,United States,650-570-4896HajimeTsukada@dayrep.com,9/5/1972,168.1,66,27.1
496,497,male,Alexander,Hueber,3868 Freed Drive,Stockton,California,95204.0,United States,AlexanderHueber@jourrapide.com1 209 762 2320,9/12/1942,194.0,72,26.3
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,ME,3852.0,United States,207-477-0579MustafaLindstrom@jourrapide.com,4/10/1959,181.1,72,24.6
500,501,female,Jinke,de Keizer,649 Nutter Street,Overland Park,MO,64110.0,United States,816-223-6007JinkedeKeizer@teleworm.us,1/13/1971,171.2,67,26.8
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,WA,98109.0,United States,ChidaluOnyekaozulu@jourrapide.com1 360 443 2060,2/13/1952,176.9,67,27.7

In [24]:
#6️⃣ Find patients whose weight is above average:
patients[patients['weight'] > patients['weight'].mean()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1
5,6,male,Rafael,Costa,1140 Willis Avenue,Daytona Beach,Florida,32114.0,United States,386-334-5237RafaelCardosoCosta@gustr.com,8/31/1931,183.9,70,26.4
9,10,female,Sophie,Cabrera,3303 Anmoore Road,New York,New York,10011.0,United States,SophieCabreraIbarra@teleworm.us1 718 795 9124,12/3/1930,194.7,64,33.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,494,female,Fen,Chin,1826 Poplar Chase Lane,Boise,ID,83702.0,United States,FenChin@gustr.com+1 (208) 388-1065,3/18/1997,195.1,68,29.7
496,497,male,Alexander,Hueber,3868 Freed Drive,Stockton,California,95204.0,United States,AlexanderHueber@jourrapide.com1 209 762 2320,9/12/1942,194.0,72,26.3
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,ME,3852.0,United States,207-477-0579MustafaLindstrom@jourrapide.com,4/10/1959,181.1,72,24.6
499,500,male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,AZ,86341.0,United States,928-284-4492RumanBisliev@gustr.com,3/26/1948,239.6,70,34.4
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,WA,98109.0,United States,ChidaluOnyekaozulu@jourrapide.com1 360 443 2060,2/13/1952,176.9,67,27.7

In [25]:
# 7️⃣ Display the tallest patient:
patients[patients['height'] == patients['height'].max()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
418,419,male,Mahmud,Kadyrov,3390 Hidden Meadow Drive,Stanton,ND,58571.0,United States,MahmudKadyrov@gustr.com1 701 745 2700,6/18/1980,215.2,79,24.2

In [28]:
# How many unique patients are there ?
patients['patient_id'].nunique()

503

In [29]:
# Gender distribution
patients['assigned_sex'].value_counts()

assigned_sex
male      253
female    250
Name: count, dtype: int64

In [31]:
# Top states and cities
patients['state'].value_counts().head()

state
California    36
TX            32
New York      25
CA            24
NY            22
Name: count, dtype: int64

In [32]:
# BMI State
patients['bmi'].describe()

count    503.000000
mean      27.483897
std        5.276438
min       17.100000
25%       23.300000
50%       27.200000
75%       31.750000
max       37.700000
Name: bmi, dtype: float64

In [35]:
# Age Distribution (calculated from bithdate)
from datetime import datetime
import pandas as pd

# Define today's date
today = pd.to_datetime("today")

# Make sure 'birthdate' is in datetime format
patients['birthdate'] = pd.to_datetime(patients['birthdate'], errors='coerce')

# Calculate age
patients['age'] = (today - patients['birthdate']).dt.days // 365

patients['age'].describe()

count    503.000000
mean      65.739563
std       22.507408
min       25.000000
25%       46.500000
50%       66.000000
75%       87.000000
max      103.000000
Name: age, dtype: float64

In [37]:
# Are there duplicate patients ?
patients.duplicated().sum()

0

# 📈 3. Diagnostic Questions (Why did it happen?)

In [39]:
# why are some values missing?
patients.isnull().sum()

patient_id       0
assigned_sex     0
given_name       0
surname          0
address         12
city            12
state           12
zip_code        12
country         12
contact         12
birthdate        0
weight           0
height           0
bmi              0
age              0
dtype: int64

In [41]:
patients[patients['address'].isnull()]['assigned_sex'].value_counts()

assigned_sex
female    7
male      5
Name: count, dtype: int64

In [44]:
patients[patients['address'].isnull()]['age'].describe()

count    12.000000
mean     57.666667
std      20.689626
min      29.000000
25%      43.250000
50%      55.000000
75%      73.250000
max      89.000000
Name: age, dtype: float64

In [45]:
# Is there a correlation between BMI and age ?
patients[['bmi','age']].corr()

          bmi       age
bmi  1.000000  0.029517
age  0.029517  1.000000

In [46]:
# Do patirnts from certain states /cities have higher average BMI?
patients.groupby('state')['bmi'].mean().sort_values(ascending=False).head()

state
WV    35.833333
MT    34.850000
AR    31.150000
WY    31.100000
KS    31.000000
Name: bmi, dtype: float64

In [47]:
# Does height have any relationship with BMI in this dataset?
patients[['height','bmi']].corr()

          height       bmi
height  1.000000 -0.254487
bmi    -0.254487  1.000000

In [52]:
 # Do patients without contact info belong to a certain demographic?
patients[patients['contact'].isnull()]['age'].mean()

57.666666666666664

In [56]:
patients[patients['contact'].notnull()]['state'].value_counts()

state
California    36
TX            32
New York      25
CA            24
NY            22
MA            22
PA            18
GA            15
Illinois      14
OH            14
OK            13
MI            13
Florida       13
LA            13
NJ            12
VA            11
MS            10
WI            10
IL            10
IN             9
MN             9
FL             9
AL             9
TN             9
WA             8
NC             8
KY             8
MO             7
ID             6
NV             6
KS             6
SC             5
IA             5
CT             5
ME             4
RI             4
Nebraska       4
ND             4
CO             4
AZ             4
AR             4
MD             3
DE             3
WV             3
SD             3
OR             3
NE             2
MT             2
VT             2
DC             2
AK             1
WY             1
NH             1
NM             1
Name: count, dtype: int64

In [57]:
# Are extremely high/low BMI values related to specific age ranges or height values?
patients[patients['bmi'] > 35][['age','height','weight']]

     age  height  weight
10    50      62   199.3
13    64      67   228.4
23    64      66   222.9
35    39      62   198.9
42    97      61   199.1
52    74      62   202.0
61    62      69   244.9
72    94      65   214.5
91    76      66   218.7
96    53      65   211.4
104   97      62   200.6
113   93      63   204.2
125   42      63   203.5
130   85      65   217.8
131   64      64   206.1
151   72      66   219.6
157   74      60   184.6
162   58      63   201.7
177   97      63   203.7
203   69      60   192.7
219   47      69   237.8
223   85      63   202.4
227   83      60   187.9
236   44      62   199.8
240   58      63   198.0
245   39      62   206.1
246   56      66   232.1
250   92      64   206.1
255   86      60   187.1
266   76      61   187.0
279   58      62   200.8
282   64      64   206.1
283   39      68   245.5
322   50      66   218.5
332   54      67   224.0
339   47      67   229.0
352   58      67   227.7
355   89      59   182.6
367   97      60   191.0
376   89      62   200.8
403   92      65   219.1
431   82      64   219.9
443   60      60   191.0
469   59      66   220.4
479   69      65   220.0
482   80      65   220.0

In [58]:
# Are younger patienta {e.g. <40} more likely to have missing location data?
patients[patients['age']<40]['address'].isnull().sum()

3

# Quality

* [Completeness ,  validity , Accuracy ,consistency]

# Cleaning Data 
 * You should follow the order provided below:
    * Completeness Issues
    * Tidiness Issues
    * Remaining Data Quality issues like validity , accuracy and consistency

## Steps incolved in data cleaning 
   * Define  
   * code 
   * text
   
` Always make sure to create a copy of your pandas dataframe before you start the cleanung process`

In [68]:
patients_copy = patients.copy()

In [74]:
patients_copy.sample(5)

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi,age
239,240,male,Khalid,Johnsrud,1147 Kelley Road,Gulfport,MS,39501.0,United States,228-378-1355KhalidJohnsrud@teleworm.us,1930-01-28,214.5,69,31.7,95
432,433,female,Karen,Jakobsen,1690 Fannie Street,Houston,TX,77020.0,United States,KarenJakobsen@jourrapide.com1 979 203 0438,1962-11-25,185.2,67,29.0,62
216,217,female,Gabrielle,Bidwill,3479 Elm Drive,Manhattan,New York,10016.0,United States,646-472-4758GabrielleBidwill@teleworm.us,1963-10-11,170.1,67,26.6,61
466,467,female,Andrea,Brodahl,3234 Sardis Station,Golden Valley,MN,55422.0,United States,AndreaBrodahl@armyspy.com+1 (612) 589-1495,1994-09-07,166.1,62,30.4,30
209,210,female,Lalita,Eldarkhanov,NaN,NaN,NaN,NaN,NaN,NaN,1950-08-14,143.4,62,26.2,74

In [69]:
patients_copy.describe()

,patient_id,zip_code,birthdate,weight,height,bmi,age
count,503.000000,491.000000,503,503.000000,503.000000,503.000000,503.000000
mean,252.000000,49084.118126,1959-02-03 15:33:16.819085504,173.434990,66.634195,27.483897,65.739563
min,1.000000,1002.000000,1921-11-06 00:00:00,48.800000,27.000000,17.100000,25.000000
25%,126.500000,21920.500000,1938-04-13 00:00:00,149.300000,63.000000,23.300000,46.500000
50%,252.000000,48057.000000,1959-04-10 00:00:00,175.300000,67.000000,27.200000,66.000000
75%,377.500000,75679.000000,1978-04-16 00:00:00,199.500000,70.000000,31.750000,87.000000
max,503.000000,99701.000000,1999-07-03 00:00:00,255.900000,79.000000,37.700000,103.000000
std,145.347859,30265.807442,NaN,33.916741,4.411297,5.276438,22.507408

In [70]:
patients_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       491 non-null    object
 5   city          491 non-null    object
 6   state         491 non-null    object
 7   zip_code      491 non-null    float64
 8   country       491 non-null    object
 9   contact       491 non-null    object
 10  birthdate     503 non-null    datetime64[ns]
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
 14  age           503 non-null    int64
dtypes: datetime64[ns](1), float64(3), int64(3), object(8)
memory usage: 59.1+ KB

In [78]:
patients_copy['assigned_sex'].isnull().sum()

0

In [76]:
patients_copy['assigned_sex'].value_counts()

assigned_sex
male      253
female    250
Name: count, dtype: int64

In [83]:
patients_copy['address'].isnull().sum()

12

In [81]:
patients_copy[patients_copy['address'].isnull()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi,age
209,210,female,Lalita,Eldarkhanov,NaN,NaN,NaN,NaN,NaN,NaN,1950-08-14,143.4,62,26.2,74
219,220,male,Mỹ,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,1978-04-09,237.8,69,35.1,47
230,231,female,Elisabeth,Knudsen,NaN,NaN,NaN,NaN,NaN,NaN,1976-09-23,165.9,63,29.4,48
234,235,female,Martina,Tománková,NaN,NaN,NaN,NaN,NaN,NaN,1936-04-07,199.5,65,33.2,89
242,243,male,John,O'Brian,NaN,NaN,NaN,NaN,NaN,NaN,1957-02-25,205.3,74,26.4,68
249,250,male,Benjamin,Mehler,NaN,NaN,NaN,NaN,NaN,NaN,1951-10-30,146.5,69,21.6,73
257,258,male,Jin,Kung,NaN,NaN,NaN,NaN,NaN,NaN,1995-05-17,231.7,69,34.2,29
264,265,female,Wafiyyah,Asfour,NaN,NaN,NaN,NaN,NaN,NaN,1989-11-03,158.6,63,28.1,35
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,1937-10-09,175.2,61,33.1,87
278,279,female,Generosa,Cabán,NaN,NaN,NaN,NaN,NaN,NaN,1962-12-16,124.3,69,18.4,62
286,287,male,Lewis,Webb,NaN,NaN,NaN,NaN,NaN,NaN,1979-04-01,155.3,68,23.6,46
296,297,female,Chỉ,Lâm,NaN,NaN,NaN,NaN,NaN,NaN,1990-05-14,181.1,63,32.1,34

In [85]:
patients[patients_copy['address'].isnull()]['assigned_sex'].value_counts()

assigned_sex
female    7
male      5
Name: count, dtype: int64

In [ ]:
patients[patients_copy['address'].isnull()]['assigned_sex'].describe()

count         12
unique         2
top       female
freq           7
Name: assigned_sex, dtype: object

In [90]:

patients_copy.sample(10)

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi,age
252,253,male,Juan,Pérez,2549 Pearlman Avenue,Bedford,MA,1730.0,United States,978-243-8596JuanPerez@teleworm.us,1991-10-01,224.2,70,32.2,33
113,114,female,Svanhvít,Guðjónsdóttir,2641 Michael Street,Houston,TX,77074.0,United States,SvanhvitGujonsdottir@cuvox.de1 713 779 6516,1931-07-23,204.2,63,36.2,93
333,334,male,Jad Allah,Gaber,2704 Windy Ridge Road,Monroeville,IN,46773.0,United States,JadAllahSayyarGaber@rhyta.com1 260 623 1176,1926-05-14,174.2,69,25.7,98
46,47,male,Javier,Moquin,1808 Stuart Street,Pittsburgh,PA,15201.0,United States,724-419-3583JavierMoquin@rhyta.com,1941-08-07,163.9,72,22.2,83
205,206,male,Breno,Correia,3539 Bottom Lane,Tonawanda,New York,14150.0,United States,716-743-5884BrenoLimaCorreia@superrito.com,1974-07-11,180.6,67,28.3,50
186,187,female,Jane,Citizen,2866 Myra Street,Providence,RI,2908.0,United States,JaneCitizen@cuvox.de+1 (401) 485-6384,1974-09-27,143.0,65,23.8,50
111,112,female,Nicole,Zimmerman,909 Williams Avenue,Newhall,California,91321.0,United States,661-291-1812NicoleZimmerman@rhyta.com,1984-01-14,225.9,74,29.0,41
386,387,male,Sargent,Flamand,163 Hide A Way Road,San Jose,California,95134.0,United States,408-215-6012SargentFlamand@dayrep.com,1965-05-10,207.7,65,34.6,59
59,60,male,Avdei,Tikhonov,1368 Yorkshire Circle,Wilson,NC,27893.0,United States,AvdeiTikhonov@gustr.com1 252 291 3898,1928-12-10,150.0,72,20.3,96
17,18,female,Roxanne,Andreyeva,2103 Edington Drive,Smyrna,GA,30082.0,United States,RoxanneAndreyeva@armyspy.com678-829-8578,1922-07-24,129.1,60,25.2,102

In [92]:
patients_copy.sample(10)

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi,age
149,150,male,Wawrzyniec,Nowakowski,1525 Crestview Terrace,Mountain Home,TX,78058.0,United States,830-640-5848WawrzyniecNowakowski@teleworm.us,1937-09-18,170.5,71,23.8,87
224,225,female,Veronika,Jindrová,3641 Selah Way,Brattleboro,VT,5301.0,United States,802-614-0812VeronikaJindrova@jourrapide.com,1981-01-15,171.4,62,31.3,44
338,339,female,Lóa,Hrafnsdóttir,3417 Bassel Street,Metairie,LA,70001.0,United States,LoaHrafnsdottir@jourrapide.com+1 (985) 335-8662,1925-04-30,114.1,67,17.9,100
194,195,male,Urso,Aranda,1330 Lincoln Street,Hopewell Mercer,NJ,8525.0,United States,609-466-3275UrsoArandaSanchez@rhyta.com,1999-07-03,163.7,70,23.5,25
493,494,female,Fen,Chin,1826 Poplar Chase Lane,Boise,ID,83702.0,United States,FenChin@gustr.com+1 (208) 388-1065,1997-03-18,195.1,68,29.7,28
464,465,female,Meaza,Brhane,142 Broad Street,Springville,AL,35146.0,United States,MeazaBrhane@superrito.com205-467-9279,1991-06-22,161.3,69,23.8,33
106,107,male,Inunnguaq,Heilmann,4110 Capitol Avenue,New Castle,IN,47362.0,United States,InunnguaqHeilmann@rhyta.com1 765 599 8847,1976-05-06,219.9,67,34.4,48
98,99,male,Jan,Baum,1733 Blackwell Street,Fairbanks,AK,99701.0,United States,JanBaum@superrito.com+1 (907) 328-4125,1967-11-06,194.3,74,24.9,57
239,240,male,Khalid,Johnsrud,1147 Kelley Road,Gulfport,MS,39501.0,United States,228-378-1355KhalidJohnsrud@teleworm.us,1930-01-28,214.5,69,31.7,95
248,249,female,Cecilie,Nilsen,1854 Kyle Street,North Loup,Nebraska,68859.0,United States,CecilieNilsen@superrito.com308-496-7837,1950-01-12,181.3,64,31.1,75

# Adverse_reactions Data Set

In [94]:
adverse_reactions_copy = adverse_reactions.copy()

In [95]:
adverse_reactions_copy.head()

  given_name     surname           adverse_reaction
0      berta  napolitani  injection site discomfort
1       lena        baer               hypoglycemia
2     joseph         day               hypoglycemia
3     flavia  fiorentino                      cough
4    manouck     wubbels          throat irritation

In [96]:
adverse_reactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   given_name        34 non-null     object
 1   surname           34 non-null     object
 2   adverse_reaction  34 non-null     object
dtypes: object(3)
memory usage: 944.0+ bytes

In [97]:
adverse_reactions_copy.describe()

       given_name  surname adverse_reaction
count          34       34               34
unique         34       33                6
top         berta  johnson     hypoglycemia
freq            1        2               19

In [99]:
adverse_reactions_copy.size

102

In [100]:
adverse_reactions_copy

     given_name     surname           adverse_reaction
0         berta  napolitani  injection site discomfort
1          lena        baer               hypoglycemia
2        joseph         day               hypoglycemia
3        flavia  fiorentino                      cough
4       manouck     wubbels          throat irritation
5       jasmine       sykes               hypoglycemia
6        louise     johnson               hypoglycemia
7       albinca     komavec               hypoglycemia
8           noe      aranda               hypoglycemia
9         sofia   hermansen  injection site discomfort
10        tegan     johnson                   headache
11         abel     yonatan                      cough
12    abdul-nur         isa               hypoglycemia
13         leon      scholz  injection site discomfort
14     gabriele     saenger               hypoglycemia
15       jia li        teng                     nausea
16        jakob    jakobsen               hypoglycemia
17  christopher    woodward                     nausea
18          ole    petersen               hypoglycemia
19       finley    chandler                   headache
20     anenechi       chidi               hypoglycemia
21     miłosław  wiśniewski  injection site discomfort
22        lixue       hsueh  injection site discomfort
23        merci      leroux               hypoglycemia
24         kang         mai  injection site discomfort
25       elliot  richardson               hypoglycemia
26      clinton      miller          throat irritation
27       idalia       moore               hypoglycemia
28       xiuxiu       chang               hypoglycemia
29         alex    crawford               hypoglycemia
30       monika      lončar               hypoglycemia
31       steven         roy                   headache
32      cecilie      nilsen               hypoglycemia
33    krisztina      magyar               hypoglycemia

In [102]:
adverse_reactions_copy.duplicated().sum()

0

In [103]:
adverse_reactions_copy.isnull().sum()

given_name          0
surname             0
adverse_reaction    0
dtype: int64

In [104]:
adverse_reactions_copy.tail()

   given_name   surname adverse_reaction
29       alex  crawford     hypoglycemia
30     monika    lončar     hypoglycemia
31     steven       roy         headache
32    cecilie    nilsen     hypoglycemia
33  krisztina    magyar     hypoglycemia

In [105]:
adverse_reactions_copy.sample()

   given_name  surname adverse_reaction
14   gabriele  saenger     hypoglycemia

In [107]:
adverse_reactions_copy['given_name'].value_counts().head()

given_name
berta       1
elliot      1
finley      1
anenechi    1
miłosław    1
Name: count, dtype: int64

In [108]:
adverse_reactions_copy.duplicated().sum()

0

In [109]:
adverse_reactions_copy['adverse_reaction'].value_counts().head()

adverse_reaction
hypoglycemia                 19
injection site discomfort     6
headache                      3
cough                         2
throat irritation             2
Name: count, dtype: int64

In [111]:
adverse_reactions_copy['adverse_reaction'].value_counts()

adverse_reaction
hypoglycemia                 19
injection site discomfort     6
headache                      3
cough                         2
throat irritation             2
nausea                        2
Name: count, dtype: int64

In [112]:
adverse_reactions_copy.groupby(['surname', 'adverse_reaction']).size().reset_index(name='count')

       surname           adverse_reaction  count
0       aranda               hypoglycemia      1
1         baer               hypoglycemia      1
2     chandler                   headache      1
3        chang               hypoglycemia      1
4        chidi               hypoglycemia      1
5     crawford               hypoglycemia      1
6          day               hypoglycemia      1
7   fiorentino                      cough      1
8    hermansen  injection site discomfort      1
9        hsueh  injection site discomfort      1
10         isa               hypoglycemia      1
11    jakobsen               hypoglycemia      1
12     johnson                   headache      1
13     johnson               hypoglycemia      1
14     komavec               hypoglycemia      1
15      leroux               hypoglycemia      1
16      lončar               hypoglycemia      1
17      magyar               hypoglycemia      1
18         mai  injection site discomfort      1
19      miller          throat irritation      1
20       moore               hypoglycemia      1
21  napolitani  injection site discomfort      1
22      nilsen               hypoglycemia      1
23    petersen               hypoglycemia      1
24  richardson               hypoglycemia      1
25         roy                   headache      1
26     saenger               hypoglycemia      1
27      scholz  injection site discomfort      1
28       sykes               hypoglycemia      1
29        teng                     nausea      1
30  wiśniewski  injection site discomfort      1
31    woodward                     nausea      1
32     wubbels          throat irritation      1
33     yonatan                      cough      1