In [100]:
import pandas as pd
import numpy as np

In [3]:
car =pd.read_csv('quikr_car.csv')

In [4]:
car.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [5]:
car.shape

(892, 6)

In [6]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [7]:
car['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [8]:
car['Price'].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '3,71,500', '4,35,000', '1,89,700', '3,89,700',
       '3,60,000', '2,95,000', '1,14,990', '10,65,000', '4,70,000',
       '48,000', '1,88,000', '4,65,000', '1,79,999', '21,90,000',
       '23,90,000', '10,75,000', '4,75,000', '10,25,000', '6,15,000',
       '19,00,000', '14,90,000', '15,10,000', '18,50,000', '7,90,000',
       '17,25,000', '12,25,000', '68,000', '9,70,000', '31,00,000',
       '8,99,000', '88,000', '53,000', '5,68,500', '71,000', '5,90,000',
       '7,95,000', '42,000', '1,89,000', '1,62,000', '35,999',
       '29,00,000', '39,999', '50,500', '5,10,000', '8,60,000',
       '5,00,001'], dtype=object)

In [9]:
car['kms_driven'].unique()

array(['45,000 kms', '40 kms', '22,000 kms', '28,000 kms', '36,000 kms',
       '59,000 kms', '41,000 kms', '25,000 kms', '24,530 kms',
       '60,000 kms', '30,000 kms', '32,000 kms', '48,660 kms',
       '4,000 kms', '16,934 kms', '43,000 kms', '35,550 kms',
       '39,522 kms', '39,000 kms', '55,000 kms', '72,000 kms',
       '15,975 kms', '70,000 kms', '23,452 kms', '35,522 kms',
       '48,508 kms', '15,487 kms', '82,000 kms', '20,000 kms',
       '68,000 kms', '38,000 kms', '27,000 kms', '33,000 kms',
       '46,000 kms', '16,000 kms', '47,000 kms', '35,000 kms',
       '30,874 kms', '15,000 kms', '29,685 kms', '1,30,000 kms',
       '19,000 kms', nan, '54,000 kms', '13,000 kms', '38,200 kms',
       '50,000 kms', '13,500 kms', '3,600 kms', '45,863 kms',
       '60,500 kms', '12,500 kms', '18,000 kms', '13,349 kms',
       '29,000 kms', '44,000 kms', '42,000 kms', '14,000 kms',
       '49,000 kms', '36,200 kms', '51,000 kms', '1,04,000 kms',
       '33,333 kms', '33,600 kms', '5,600 kms', '7,500 kms', '26,000 kms',
       '24,330 kms', '65,480 kms', '28,028 kms', '2,00,000 kms',
       '99,000 kms', '2,800 kms', '21,000 kms', '11,000 kms',
       '66,000 kms', '3,000 kms', '7,000 kms', '38,500 kms', '37,200 kms',
       '43,200 kms', '24,800 kms', '45,872 kms', '40,000 kms',
       '11,400 kms', '97,200 kms', '52,000 kms', '31,000 kms',
       '1,75,430 kms', '37,000 kms', '65,000 kms', '3,350 kms',
       '75,000 kms', '62,000 kms', '73,000 kms', '2,200 kms',
       '54,870 kms', '34,580 kms', '97,000 kms', '60 kms', '80,200 kms',
       '3,200 kms', '0,000 kms', '5,000 kms', '588 kms', '71,200 kms',
       '1,75,400 kms', '9,300 kms', '56,758 kms', '10,000 kms',
       '56,450 kms', '56,000 kms', '32,700 kms', '9,000 kms', '73 kms',
       '1,60,000 kms', '84,000 kms', '58,559 kms', '57,000 kms',
       '1,70,000 kms', '80,000 kms', '6,821 kms', '23,000 kms',
       '34,000 kms', '1,800 kms', '4,00,000 kms', '48,000 kms',
       '90,000 kms', '12,000 kms', '69,900 kms', '1,66,000 kms',
       '122 kms', '0 kms', '24,000 kms', '36,469 kms', '7,800 kms',
       '24,695 kms', '15,141 kms', '59,910 kms', '1,00,000 kms',
       '4,500 kms', '1,29,000 kms', '300 kms', '1,31,000 kms',
       '1,11,111 kms', '59,466 kms', '25,500 kms', '44,005 kms',
       '2,110 kms', '43,222 kms', '1,00,200 kms', '65 kms',
       '1,40,000 kms', '1,03,553 kms', '58,000 kms', '1,20,000 kms',
       '49,800 kms', '100 kms', '81,876 kms', '6,020 kms', '55,700 kms',
       '18,500 kms', '1,80,000 kms', '53,000 kms', '35,500 kms',
       '22,134 kms', '1,000 kms', '8,500 kms', '87,000 kms', '6,000 kms',
       '15,574 kms', '8,000 kms', '55,800 kms', '56,400 kms',
       '72,160 kms', '11,500 kms', '1,33,000 kms', '2,000 kms',
       '88,000 kms', '65,422 kms', '1,17,000 kms', '1,50,000 kms',
       '10,750 kms', '6,800 kms', '5 kms', '9,800 kms', '57,923 kms',
       '30,201 kms', '6,200 kms', '37,518 kms', '24,652 kms', '383 kms',
       '95,000 kms', '3,528 kms', '52,500 kms', '47,900 kms',
       '52,800 kms', '1,95,000 kms', '48,008 kms', '48,247 kms',
       '9,400 kms', '64,000 kms', '2,137 kms', '10,544 kms', '49,500 kms',
       '1,47,000 kms', '90,001 kms', '48,006 kms', '74,000 kms',
       '85,000 kms', '29,500 kms', '39,700 kms', '67,000 kms',
       '19,336 kms', '60,105 kms', '45,933 kms', '1,02,563 kms',
       '28,600 kms', '41,800 kms', '1,16,000 kms', '42,590 kms',
       '7,400 kms', '54,500 kms', '76,000 kms', '00 kms', '11,523 kms',
       '38,600 kms', '95,500 kms', '37,458 kms', '85,960 kms',
       '12,516 kms', '30,600 kms', '2,550 kms', '62,500 kms',
       '69,000 kms', '28,400 kms', '68,485 kms', '3,500 kms',
       '85,455 kms', '63,000 kms', '1,600 kms', '77,000 kms',
       '26,500 kms', '2,875 kms', '13,900 kms', '1,500 kms', '2,450 kms',
       '1,625 kms', '33,400 kms', '60,123 kms', '38,900 kms',
       '1,37,495 kms', '91,200 kms', '1,46,000 kms', '1,00,800 kms',
       '2,100 kms', '2,500 kms', '1,32,000 kms', 'Petrol'], dtype=object)

In [10]:
car['fuel_type'].unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

## Quality

- year has many non-year values
- year object ot int 
- Price has ask for price
- Price object to int 
- kms_drien has kms with integers
- kms_drivern object to int 
- kms_driven has nan values
- Fuel_type has nan values
- keep first 3 words of name

## Cleaning

In [11]:
backup = car.copy()

In [16]:
## year has many non-year values
car['year']

0      2007
1      2006
2      2018
3      2014
4      2014
       ...
886    2009
888    2018
889    2013
890    2014
891    2014
Name: year, Length: 842, dtype: object

In [17]:
car['year'].str.isnumeric()

0      True
1      True
2      True
3      True
4      True
       ...
886    True
888    True
889    True
890    True
891    True
Name: year, Length: 842, dtype: bool

In [18]:
car[car['year'].str.isnumeric()]

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
886,Toyota Corolla Altis,Toyota,2009,"3,00,000","1,32,000 kms",Petrol
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [19]:
car= car[car['year'].str.isnumeric()]

In [21]:
# year object to int
car['year'].astype(int)

0      2007
1      2006
2      2018
3      2014
4      2014
       ...
886    2009
888    2018
889    2013
890    2014
891    2014
Name: year, Length: 842, dtype: int32

In [22]:
car['year'] = car['year'].astype(int)

In [24]:
# price has "ask for price"
car['Price'].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '4,35,000', '1,89,700', '3,89,700', '3,60,000',
       '2,95,000', '1,14,990', '10,65,000', '4,70,000', '48,000',
       '1,88,000', '4,65,000', '1,79,999', '21,90,000', '23,90,000',
       '10,75,000', '4,75,000', '10,25,000', '6,15,000', '19,00,000',
       '14,90,000', '15,10,000', '18,50,000', '7,90,000', '17,25,000',
       '12,25,000', '68,000', '9,70,000', '31,00,000', '8,99,000',
       '88,000', '53,000', '5,68,500', '71,000', '5,90,000', '7,95,000',
       '42,000', '1,89,000', '1,62,000', '35,999', '29,00,000', '39,999',
       '50,500', '5,10,000', '8,60,000', '5,00,001'], dtype=object)

In [25]:
car[car["Price"] != "Ask For Price"]

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
6,Ford Figo,Ford,2012,"1,75,000","41,000 kms",Diesel
...,...,...,...,...,...,...
886,Toyota Corolla Altis,Toyota,2009,"3,00,000","1,32,000 kms",Petrol
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [26]:
car = car[car["Price"] != "Ask For Price"]

In [28]:
# price remove comma and  convert it into object to int 
car['Price'].str.replace(',','').astype(int)

0       80000
1      425000
3      325000
4      575000
6      175000
        ...
886    300000
888    260000
889    390000
890    180000
891    160000
Name: Price, Length: 819, dtype: int32

In [29]:
car['Price']= car['Price'].str.replace(',','').astype(int)

C:\Users\USER\AppData\Local\Temp\ipykernel_11192\3820408130.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car['Price']= car['Price'].str.replace(',','').astype(int)

In [31]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    int32
 3   Price       819 non-null    int32
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int32(2), object(4)
memory usage: 38.4+ KB

In [33]:
## kms_drien has kms with integers
car['kms_driven']

0        45,000 kms
1            40 kms
3        28,000 kms
4        36,000 kms
6        41,000 kms
           ...
886    1,32,000 kms
888      27,000 kms
889      40,000 kms
890          Petrol
891          Petrol
Name: kms_driven, Length: 819, dtype: object

In [39]:
car['kms_driven'].str.split(" ").str.get(0).str.replace(",","")

0       45000
1          40
3       28000
4       36000
6       41000
        ...
886    132000
888     27000
889     40000
890    Petrol
891    Petrol
Name: kms_driven, Length: 819, dtype: object

In [40]:
car['kms_driven'] = car['kms_driven'].str.split(" ").str.get(0).str.replace(",","")

C:\Users\USER\AppData\Local\Temp\ipykernel_11192\3828150789.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car['kms_driven'] = car['kms_driven'].str.split(" ").str.get(0).str.replace(",","")

In [41]:
## remove Petrol form number and convert object in int 
car[car['kms_driven'].str.isnumeric()]

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
6,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
886,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
888,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
889,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [42]:
car = car[car['kms_driven'].str.isnumeric()]

In [45]:
car['kms_driven'] = car['kms_driven'].astype(int)

C:\Users\USER\AppData\Local\Temp\ipykernel_11192\2340783488.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car['kms_driven'] = car['kms_driven'].astype(int)

In [46]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int32
 3   Price       817 non-null    int32
 4   kms_driven  817 non-null    int32
 5   fuel_type   816 non-null    object
dtypes: int32(3), object(3)
memory usage: 35.1+ KB

In [47]:
## remove nan
car[car['fuel_type'].isna()]

               name company  year   Price  kms_driven fuel_type
132  Toyota Corolla  Toyota  2009  275000       26000       NaN

In [49]:
car = car[~car['fuel_type'].isna()]

In [50]:
# keep  three words form the name 
car['name']

0        Hyundai Santro Xing XO eRLX Euro III
1                     Mahindra Jeep CL550 MDI
3      Hyundai Grand i10 Magna 1.2 Kappa VTVT
4            Ford EcoSport Titanium 1.5L TDCi
6                                   Ford Figo
                        ...
883                Maruti Suzuki Ritz VXI ABS
885                 Tata Indica V2 DLE BS III
886                      Toyota Corolla Altis
888                       Tata Zest XM Diesel
889                        Mahindra Quanto C8
Name: name, Length: 816, dtype: object

In [51]:
car['name'].str.split(" ")

0        [Hyundai, Santro, Xing, XO, eRLX, Euro, III]
1                        [Mahindra, Jeep, CL550, MDI]
3      [Hyundai, Grand, i10, Magna, 1.2, Kappa, VTVT]
4              [Ford, EcoSport, Titanium, 1.5L, TDCi]
6                                        [Ford, Figo]
                            ...
883                  [Maruti, Suzuki, Ritz, VXI, ABS]
885                  [Tata, Indica, V2, DLE, BS, III]
886                          [Toyota, Corolla, Altis]
888                          [Tata, Zest, XM, Diesel]
889                            [Mahindra, Quanto, C8]
Name: name, Length: 816, dtype: object

In [52]:
car['name'].str.split(" ").str.slice(0,3)

0         [Hyundai, Santro, Xing]
1         [Mahindra, Jeep, CL550]
3           [Hyundai, Grand, i10]
4      [Ford, EcoSport, Titanium]
6                    [Ford, Figo]
                  ...
883        [Maruti, Suzuki, Ritz]
885            [Tata, Indica, V2]
886      [Toyota, Corolla, Altis]
888              [Tata, Zest, XM]
889        [Mahindra, Quanto, C8]
Name: name, Length: 816, dtype: object

In [54]:
car['name'] = car['name'].str.split(" ").str.slice(0,3).str.join(" ")

In [55]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
883      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
885          Tata Indica V2      Tata  2009  110000       30000    Diesel
886    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
888            Tata Zest XM      Tata  2018  260000       27000    Diesel
889      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [59]:
car = car.reset_index(drop=True)

In [60]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
812          Tata Indica V2      Tata  2009  110000       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
814            Tata Zest XM      Tata  2018  260000       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [61]:
car.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [63]:
car[car['Price'] >6e6]

                   name   company  year    Price  kms_driven fuel_type
534  Mahindra XUV500 W6  Mahindra  2014  8500003       45000    Diesel

In [64]:
# find the car which is above of of 6e6 so it is an outlier
car = car[car['Price']<6e6].reset_index(drop=True)

In [65]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [66]:
car.to_csv('Cleaned Car.csv')

# Model

In [68]:
# split the data for training
X= car.drop(columns='Price')
y = car['Price']

In [69]:
X

                       name   company  year  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006          40    Diesel
2         Hyundai Grand i10   Hyundai  2014       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014       36000    Diesel
4                 Ford Figo      Ford  2012       41000    Diesel
..                      ...       ...   ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011       50000    Petrol
811          Tata Indica V2      Tata  2009       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009      132000    Petrol
813            Tata Zest XM      Tata  2018       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013       40000    Diesel

[815 rows x 5 columns]

In [70]:
y

0       80000
1      425000
2      325000
3      575000
4      175000
        ...
810    270000
811    110000
812    300000
813    260000
814    390000
Name: Price, Length: 815, dtype: int32

In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [75]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [73]:
ohe  = OneHotEncoder()
ohe.fit(X[['name','company','fuel_type']])

OneHotEncoder()

In [82]:
column_trans = make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']), remainder='passthrough')

In [83]:
lr = LinearRegression()
pipe = make_pipeline(column_trans, lr)

In [84]:
pipe.fit(X_train,y_train)

c:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\compose\_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [91]:
y_pred = pipe.predict(X_test)

In [92]:
r2_score(y_test , y_pred )

0.4865410133660304

In [108]:
scores = []
for i in range(1000):
    X_train, X_test, y_train,y_test  = train_test_split(X,y,test_size=0.2,random_state=i)
    lr = LinearRegression()
    pipe = make_pipeline(column_trans,lr)
    pipe.fit(X_train, y_train)
    y_pred  =pipe.predict(X_test)
    scores.append(r2_score(y_test, y_pred))

In [109]:
scores

[0.6589775490516477,
 0.47859534625114053,
 0.6206184325887315,
 0.5370851059720391,
 0.8189003209843422,
 0.6634592678218548,
 0.627651080774843,
 0.6298500612485975,
 0.6721337147755825,
 0.569999290976279,
 0.648410356051369,
 0.6085830042105451,
 0.4570387283628752,
 0.6674701982444136,
 0.5667086409016293,
 0.710110955902248,
 0.48789129723115376,
 0.6657624958397428,
 0.6089284148932655,
 0.6397685755956675,
 0.6410709224098974,
 0.6210283939684125,
 0.7366931810218385,
 0.6403435054918312,
 0.5492294440786976,
 0.49865430736412675,
 0.6732835680238167,
 0.7035631613026931,
 0.7254576384148604,
 0.6010349558544669,
 0.6245053608697559,
 0.6290270877645332,
 0.7651654313017575,
 0.7853874888796626,
 0.5622385517206983,
 0.685024845194027,
 0.5779619998835577,
 0.6170146213581826,
 0.5393853480656206,
 0.7164312140567131,
 0.32666867715670367,
 0.6733782138107586,
 0.5731311949541246,
 0.6659932444752472,
 0.6604128224175608,
 0.6975409772585117,
 0.5258705780715188,
 0.5882064290521126,
 0.7540188120977028,
 0.6861734869122942,
 0.5038058588989355,
 0.5964725808936133,
 0.6325679093210963,
 0.6638066957559459,
 0.5797623627769186,
 0.6974693540090504,
 0.7171752768166924,
 0.7195081853284038,
 0.760859173432595,
 0.48428354013704156,
 0.5849349181102559,
 0.5244371253247728,
 0.4330340417620896,
 0.6189051514339482,
 0.607522089011671,
 0.6349243275736114,
 0.4810243158116734,
 0.6590615854542154,
 0.6214586085522245,
 0.743274946513606,
 0.6997074685617691,
 0.718579504415433,
 0.5796151530076887,
 0.7034350832805074,
 0.5518161471757719,
 0.5694855898282613,
 0.44927656745228084,
 0.6050835178219862,
 0.5738343223155049,
 0.6460411861883026,
 0.5886213603663246,
 0.5856527297265843,
 0.6765398800588244,
 0.744922939021712,
 0.6389826087094421,
 0.6358498527695688,
 0.6852016031039259,
 0.5373334373438552,
 0.6030204267549185,
 0.638377009894445,
 0.6809872042573941,
 0.5840677085925137,
 0.6883266712274796,
 0.4945068201935203,
 0.6331518312398363,
 0.6589982197584234,
 0.6383970274949671,
 0.685671676550484,
 0.6751357998207606,
 0.5924046045484042,
 0.6899601939018103,
 0.6600102221531261,
 0.683756615453387,
 0.6149163121355778,
 0.7041215445534494,
 0.5649578310778633,
 0.6078455341307166,
 0.5764028894036719,
 0.5851033777036474,
 0.7107005842382339,
 0.6766878812600473,
 0.659598128547024,
 0.5127821712678797,
 0.6956098077498688,
 0.712808743027473,
 0.5676531508773566,
 0.5902229692039391,
 0.6525735835868977,
 0.5256896650072882,
 0.7228177121081314,
 0.6581692762564109,
 0.5953147521353028,
 0.7076577689835495,
 0.6261015053194339,
 0.8216326112181462,
 0.681005019606276,
 0.637730870806759,
 0.6239460016246308,
 0.5864202001321324,
 0.550372528804032,
 0.6062859286221297,
 0.5323297110123215,
 0.6591277884511229,
 0.5821127184549941,
 0.7027029489715686,
 0.7148873283691211,
 0.5440179467037363,
 0.7128697273498124,
 0.6494389093638127,
 0.5590970714802499,
 0.7181361400409276,
 0.586705867369776,
 0.6612224480626586,
 0.7165643911721142,
 0.6245318632189201,
 0.5545537312096575,
 0.6359565804596823,
 0.588046184004918,
 0.5634737924621669,
 0.6069053339472597,
 0.6277211437794104,
 0.7724596338646768,
 0.565661196840624,
 0.5011852453586854,
 0.634135305666903,
 0.658846905817982,
 0.41606685035235824,
 0.7312052473847346,
 0.6297170749145033,
 0.6780739468150099,
 0.6478383058539585,
 0.581544526951242,
 0.6642600005835593,
 0.5706479505342106,
 0.54079496160464,
 0.6904361318757128,
 0.6572538443831808,
 0.48755369980445395,
 0.5687885149270496,
 0.6962773342371886,
 0.6922986141878773,
 0.6496643915200366,
 0.8164623049986885,
 0.718992939258467,
 0.5470821486753814,
 0.6143164502192797,
 0.7019970068120145,
 0.6112378221197254,
 0.7144213545366009,
 0.6795652793537643,
 0.6414515027744365,
 0.6170223210884662,
 0.6744829735207113,
 0.638957043691846,
 0.5049458053870068,
 0.6668450507209176,
 0.7358344497092881,
 0.687191073672583,
 0.6957933389418236,
 0.5728625851958813,
 0.7118277958664974,
 0.6646766794442025,
 0.579138851056737,
 0.6910788510484065,
 0.7292967069082062,
 0.6272207042044369,
 0.6315943191591371,
 0.7494009751972648,
 0.40231095224801017,
 0.7100659355621983,
 0.7154939229750867,
 0.45221334912847166,
 0.6115894971535283,
 0.7847693437331795,
 0.5828448545470719,
 0.7267676887729266,
 0.7711396213904578,
 0.5696036103014482,
 0.6767090630817606,
 0.3007879590164988,
 0.49257246733488314,
 0.5097936446676645,
 0.5691023806941338,
 0.6185929464484128,
 0.6759133226274681,
 0.6179569497577726,
 0.5303632563728018,
 0.6362584065335504,
 0.5417923705224519,
 0.5760916790679342,
 0.5905489510022623,
 0.6818009905460174,
 0.4754815031310341,
 0.49581214147159736,
 0.5517618814834195,
 0.7244657270988821,
 0.7406195756855021,
 0.6385679809470548,
 0.7309062731488489,
 0.5782879205308271,
 0.5551335353250881,
 0.5933498377668951,
 0.6307955710341127,
 0.4406629424695129,
 0.724503896010246,
 0.586696192238807,
 0.701015763803895,
 0.6090762393264832,
 0.5266450673911242,
 0.5940629263260737,
 0.5705695823833171,
 0.48454448375728754,
 0.5171441695827779,
 0.63995423553897,
 0.49584118736915606,
 0.7214297947765057,
 0.7796528629406407,
 0.7463062054569278,
 0.7799755460442197,
 0.543251051307208,
 0.6070998323214498,
 0.5083576250416957,
 0.5594153451493236,
 0.6510105640213559,
 0.5879417389945629,
 0.7699200009699592,
 0.559098383468555,
 0.6989268162691123,
 0.6601917740280057,
 0.5644983703485787,
 0.7154231110734142,
 0.7578394407335575,
 0.7048056324203738,
 0.7703171370590804,
 0.6347475984944395,
 0.5753635804860852,
 0.6586435895016174,
 0.6530084076580638,
 0.47476497716609756,
 0.5431659610279091,
 0.6272521191656313,
 0.5494026272230386,
 0.6220939317933835,
 0.617718455483529,
 0.715718886517769,
 0.628051483052195,
 0.7534293213562041,
 0.6969007525333072,
 0.6287015152260966,
 0.7884257210708662,
 0.6738637122231711,
 0.6544793734134398,
 0.6888912549388737,
 0.7344565980437592,
 0.717367605966728,
 0.5664224229554538,
 0.7224627867702149,
 0.5928211901636238,
 0.3849964409173614,
 0.45187066479110416,
 0.5199589141742247,
 0.6925845303182564,
 0.5407270156626004,
 0.7509819254014263,
 0.8132026476822222,
 0.6309730927488564,
 0.7431581573463812,
 0.7010412394197354,
 0.5330360736964104,
 0.6835420005115413,
 0.7690985544612867,
 0.7091754823868064,
 0.7634552773684578,
 0.48720695846269413,
 0.6521287709580831,
 0.5960583440913522,
 0.7878602283910798,
 0.6918057710083833,
 0.6490680688323722,
 0.696959823846441,
 0.6748556884234747,
 0.6069460756693468,
 0.5083068118708942,
 0.49942307520223916,
 0.5282074740228453,
 0.7374967421608402,
 0.5830901283409312,
 0.6074540941783003,
 0.653861252929492,
 0.5117568838602597,
 0.4756574646678432,
 0.5930869233062218,
 0.5330768783410326,
 0.5478043422123094,
 0.6196842257169537,
 0.5365585022571019,
 0.592806748124981,
 0.7232925949354405,
 0.6937351731472201,
 0.5143811342536755,
 0.653705150824555,
 0.502395819988567,
 0.6012789223908226,
 0.5731418740216581,
 0.6980506229895307,
 0.6015744725904919,
 0.5096215663914591,
 0.6708955908137405,
 0.6187269329740095,
 0.5840136031184426,
 0.7273559250139529,
 0.7318998894769165,
 0.5999653106643426,
 0.6714103418465805,
 0.6914680473314039,
 0.6448592637905641,
 0.6674358800100854,
 0.5895183291313577,
 0.705008413439635,
 0.6225986599643787,
 0.7436060829417994,
 0.7074400766978081,
 0.574243524784535,
 0.4603091115724156,
 0.728609034419164,
 0.6677603224863372,
 0.6984814672912064,
 0.6428797868061968,
 0.7076424292600532,
 0.5834397742434172,
 0.7067893925689152,
 0.6772115624397397,
 0.5385689925973852,
 0.695210784239148,
 0.7148432124497638,
 0.5628547160003579,
 0.6814875547156312,
 0.41687094645322753,
 0.7446908145713529,
 0.733920478799122,
 0.6802116225232707,
 0.6248997240398568,
 0.6434083336658589,
 0.6603125986727839,
 0.5147710764186529,
 0.5618444188026526,
 0.6845763439179546,
 0.5392514737249156,
 0.7351535461759946,
 0.770203406630189,
 0.6190280923459994,
 0.692908033812617,
 0.7054265531234298,
 0.8071026681861865,
 0.6887520674634988,
 0.7047053802578054,
 0.6714530931599464,
 0.5959186527582441,
 0.5647714514472667,
 0.43467755846083644,
 0.7343567712929087,
 0.5622026707008723,
 0.8082355234415374,
 0.3785261940481044,
 0.6367668701231886,
 0.7303975637848203,
 0.5506422667992849,
 0.5941423531836068,
 0.7003249041166559,
 0.7190952366541454,
 0.6332984076531964,
 0.5884207070981717,
 0.5586624136170235,
 0.47188942614212026,
 0.6155797743082658,
 0.6504013988202317,
 0.574563275574332,
 0.6631422182699913,
 0.6844591813642291,
 0.6685712368381627,
 0.6861809620025414,
 0.6551661250141274,
 0.6563906856831183,
 0.5172204196342414,
 0.5840060116097172,
 0.5545966187607133,
 0.4703098353163475,
 0.6928245536169544,
 0.6768312140258946,
 0.6702128491390209,
 0.6703514014912952,
 0.6646964761529467,
 0.6886343146254581,
 0.6500247135819359,
 0.628185039182614,
 0.5793689710265938,
 0.43460648641396915,
 0.7407225088724834,
 0.5300822143702807,
 0.6585944568509121,
 0.6815981787835212,
 0.774571695251632,
 0.6472009509195371,
 0.8457059012561223,
 0.6070928569224234,
 0.7763096119898374,
 0.5834897971507693,
 0.7060975479007643,
 0.6449218250640104,
 0.7164553067593833,
 0.6412368878543147,
 0.6707424049304609,
 0.5888021848989438,
 0.8022163666838086,
 0.7720577246760695,
 0.7426092980061625,
 0.7215365895371424,
 0.6240906927906877,
 0.5661459077573998,
 0.7531301289788755,
 0.7764757043928467,
 0.5497230190890452,
 0.5775080195308353,
 0.6333031699169267,
 0.6490683129554451,
 0.640373388831639,
 0.5001154622364761,
 0.5133047242467599,
 0.742725231983173,
 0.6464478082239539,
 0.7460968108371793,
 0.5490086807360186,
 0.5891680602589313,
 0.773318489506982,
 0.5096239214758277,
 0.6222397321173196,
 0.6797955420227421,
 0.5989924845690933,
 0.6808168195754604,
 0.6499513791917747,
 0.49057550593625443,
 0.5428246335561079,
 0.35083034616278086,
 0.7225174557580823,
 0.7031291590763904,
 0.7743415745267525,
 0.6185379669604052,
 0.6266998387042759,
 0.7329133176560831,
 0.5341704411755206,
 0.5773043133400994,
 0.600266741189873,
 0.6093144827133368,
 0.5348492312756437,
 0.5553401776149893,
 0.5177969821799173,
 0.6340228636437025,
 0.5806153727994809,
 0.7400523612380987,
 0.6327805820949264,
 0.49488702018281705,
 0.7762503095386587,
 0.6032630395443116,
 0.6247740007090302,
 0.6711122289571748,
 0.5868831956315944,
 0.7010716401126116,
 0.6498569099606533,
 0.6625432029481871,
 0.7793310805506639,
 0.6825623422672206,
 0.5996108721340782,
 0.5605338003591188,
 0.6312601234412798,
 0.5000844100276749,
 0.652574485690624,
 0.6720564269551852,
 0.7637754542828896,
 0.6871338890049421,
 0.6535172518210054,
 0.6423974233595697,
 0.6289698701799169,
 0.6376745875764909,
 0.7256045256165446,
 0.6604021636492741,
 0.7836016060534645,
 0.7193366339311691,
 0.7590948025077358,
 0.5945450822668743,
 0.6750954016309405,
 0.6941294394586305,
 0.6772477933473262,
 0.49798264137353254,
 0.5697533325952704,
 0.5324634711426061,
 0.4839352594486417,
 0.6351559252147158,
 0.6890267720662264,
 0.7635498521536781,
 0.6536058078360557,
 0.6277303999842448,
 0.5634339226470558,
 0.6366455040477079,
 0.7375394192059631,
 0.5087371121666737,
 0.5794101397396703,
 0.6378707471406821,
 0.5298673670612039,
 0.6776950690487635,
 0.5758311863555947,
 0.6923439572688472,
 0.6007479630650996,
 0.679022170540853,
 0.5428827651844024,
 0.6958772459465143,
 0.4634330348292337,
 0.7139001197336239,
 0.32349551830379664,
 0.7312973693168721,
 0.502036771952693,
 0.6214109806057933,
 0.6739569873627402,
 0.5334869134884346,
 0.7245118300922027,
 0.6237910982663918,
 0.7147271794005621,
 0.5554056987557413,
 0.5144460898348145,
 0.6955447100783995,
 0.7086488272497381,
 0.6402147457472809,
 0.4898633814235702,
 0.7054063234995787,
 0.5894121144896811,
 0.6591654834225076,
 0.6744959902661096,
 0.8058476269442524,
 0.660168799404973,
 0.7187213346704868,
 0.656315948580052,
 0.640346035236442,
 0.6471131068408411,
 0.68501943320405,
 0.6244041833004714,
 0.5746227374894795,
 0.6950908525240875,
 0.6786344633611716,
 0.7594158025029736,
 0.6666163760746033,
 0.6317935710140046,
 0.5933415283567414,
 0.6461129230793585,
 0.4971858856460327,
 0.6070040034501856,
 0.5219282161086334,
 0.5789376387446059,
 0.6937920611088029,
 0.6380343077181612,
 0.7001237188834047,
 0.6931587758358162,
 0.589613853767417,
 0.6971778834210502,
 0.7184435619713747,
 0.7177844949524907,
 0.6080060705311422,
 0.36843500719939615,
 0.5581886737458528,
 0.5620460226582105,
 0.5643338243449592,
 0.4836017592877714,
 0.520601909036016,
 0.57062314412116,
 0.7111534920882998,
 0.5858083105189922,
 0.5208569403187893,
 0.7394849574689798,
 0.4860208456484423,
 0.6077899189255362,
 0.6830944237756171,
 0.5924797568903368,
 0.503741866319345,
 0.5916159434104071,
 0.6184811168125165,
 0.5967613679456015,
 0.6679021724614079,
 0.5918355433427994,
 0.3712641921594322,
 0.5820940234468542,
 0.6802629302136666,
 0.6069615509839954,
 0.5097083153400968,
 0.7211793935054753,
 0.6030065263929456,
 0.5126282441053645,
 0.7560295480542806,
 0.595880713681622,
 0.6934811190490241,
 0.5129646088698299,
 0.6716333825085031,
 0.6444213917064177,
 0.5865133371616974,
 0.7423315255770468,
 0.7036440040934724,
 0.6432878690857264,
 0.516043621760645,
 0.5842714800657411,
 0.678954061506402,
 0.6658581428793702,
 0.7502173209099525,
 0.5433062530602963,
 0.5651080711199105,
 0.6711240983754169,
 0.6799225506976234,
 0.6024420865686864,
 0.48496921912974045,
 0.6955596371380334,
 0.5976667066979717,
 0.47749501923898596,
 0.6039819840507802,
 0.6484908068973942,
 0.6773701244307693,
 0.6153756119396969,
 0.7503716227894297,
 0.7690479564742826,
 0.6502214004016075,
 0.6499170573308479,
 0.5854185343026637,
 0.4607428317138187,
 0.6752814741948084,
 0.6821504662648222,
 0.7256059264961146,
 0.7687202450532246,
 0.5482915607120823,
 0.5151544583307905,
 0.47981647935129446,
 0.6709485697457123,
 0.620797815000086,
 0.6989540912395229,
 0.7160674934197228,
 0.7371368703511274,
 0.750408048346605,
 0.5285881635439451,
 0.6650656892333426,
 0.7328888091572108,
 0.6646522939547059,
 0.6286915371128862,
 0.6620522272329038,
 0.580544094651049,
 0.7178182542533155,
 0.6584680561940521,
 0.6211612580425392,
 0.5341078095589639,
 0.7208021923128907,
 0.6986235429739878,
 0.5897628016392906,
 0.6219794533075139,
 0.8314094710916703,
 0.6331105488784489,
 0.5682084226828434,
 0.7932082110104884,
 0.6068264700774753,
 0.6814867365595954,
 0.6493555026494239,
 0.6541366073798509,
 0.6936087454685118,
 0.7115344979702538,
 0.6608473156595109,
 0.5533643434665036,
 0.7516686959747855,
 0.6663287130464912,
 0.4769683790039032,
 0.703970319362559,
 0.569349854153731,
 0.7294056519207165,
 0.5353067806760579,
 0.6827143869429618,
 0.7276384534013076,
 0.6506307147043293,
 0.654967420199486,
 0.5332638888868795,
 0.6449180077721488,
 0.67828974439056,
 0.8112927234641926,
 0.8016138691504251,
 0.6574811589993625,
 0.6778560351554523,
 0.7205307277635675,
 0.7319862748600772,
 0.342157956744246,
 0.6459366388460294,
 0.5558849344541437,
 0.5874014887584791,
 0.6768858727320299,
 0.6850187785757647,
 0.6417853696358538,
 0.6219732055396946,
 0.6520431759801314,
 0.6891877163533686,
 0.5977147355611417,
 0.5800401351896509,
 0.7311636169497431,
 0.5285990463617949,
 0.794035778808259,
 0.6719937709316615,
 0.588918165828143,
 0.539719519523353,
 0.6129810097182005,
 0.5038430937469849,
 0.7121561986889431,
 0.5900917167733708,
 0.6287809940174569,
 0.5936889130466005,
 0.7512070611989259,
 0.7377803305145351,
 0.5899940154898805,
 0.613089620966345,
 0.6355443983815836,
 0.5530146610643747,
 0.5925678075312257,
 0.5104278521719328,
 0.5421742017307086,
 0.7059011137170863,
 0.7641006175290559,
 0.6888752015249358,
 0.7142823435628344,
 0.6199513838804112,
 0.6012121295581832,
 0.7817593823975543,
 0.6030104404897585,
 0.6332442245440728,
 0.6523195246784872,
 0.6657742978724444,
 0.7119968987268163,
 0.643066993547967,
 0.6178649740426384,
 0.6603847365753781,
 0.6257961439925633,
 0.6269433605808036,
 0.534414931949283,
 0.7578429211953058,
 0.6724888177214726,
 0.6976764695985096,
 0.6907323084617606,
 0.6079935264263288,
 0.557744135045614,
 0.5850865297787351,
 0.5658841507042611,
 0.3626629191973141,
 0.7044522471239911,
 0.669442716913278,
 0.6546782214619683,
 0.8251847678136841,
 0.7108848293472187,
 0.7833624172942832,
 0.6409217674936982,
 0.6341855709439319,
 0.6375290671661278,
 0.6629468480456234,
 0.7001428763936259,
 0.4309483209553463,
 0.7190150655200593,
 0.702849732596293,
 0.7349627348533597,
 0.7383327650018485,
 0.6578212312720373,
 0.5603501937162833,
 0.7151474799295314,
 0.6066251568139706,
 0.6344539450944935,
 0.7392934635214914,
 0.640662280241113,
 0.5072199929869678,
 0.613092229717225,
 0.6533081212544165,
 0.544804016553514,
 0.5976212011851172,
 0.6454587178934581,
 0.7460073804630084,
 0.3888163747012312,
 0.5655178651772834,
 0.5549881989414334,
 0.6485803311359102,
 0.6712870973101708,
 0.5258502189848162,
 0.788134825964515,
 0.627791219626793,
 0.5990356389331464,
 0.7028447534684152,
 0.6569188072845444,
 0.6534843553561328,
 0.5586351382782161,
 0.7774258067289344,
 0.6599073767154997,
 0.5951109709434372,
 0.44789727703342164,
 0.7354508786961548,
 0.6643146645502507,
 0.7601259187880416,
 0.653889119059629,
 0.6380225260382689,
 0.48146266817024874,
 0.7088480302880114,
 0.775228533354464,
 0.5773696354055919,
 0.7433050138823587,
 0.6403091177040254,
 0.5846089132403487,
 0.6388387861525615,
 0.657239094830399,
 0.5945764016047133,
 0.7293166571779215,
 0.7584263302697054,
 0.7251575848817073,
 0.7080810985332808,
 0.6551090668115114,
 0.4946328857451415,
 0.6089834157963299,
 0.6132967600018218,
 0.5751253750401567,
 0.6888946039024652,
 0.7278866964987165,
 0.6005440631468644,
 0.6351597920611435,
 0.622782414721728,
 0.5506788456909715,
 0.6258064942712213,
 0.542111034770432,
 0.502353129031959,
 0.7453819269468143,
 0.5257409493566068,
 0.7757921262002948,
 0.5784671886288342,
 0.6609374095384164,
 0.5780308753036774,
 0.6640093983802695,
 0.5523371273548746,
 0.6233613429061409,
 0.6024021267338762,
 0.5678898124848493,
 0.6332355438363295,
 0.574985978746158,
 0.46720102876045433,
 0.658005199022976,
 0.6209484314148456,
 0.6865225219299413,
 0.6563598823091727,
 0.6481739434589523,
 0.5438121362712642,
 0.6436172628457217,
 0.7015271149365765,
 0.6955835060752169,
 0.6988647048412784,
 0.6545587133703553,
 0.7297093544431017,
 0.7326879314349821,
 0.6279695469975879,
 0.5393371335359636,
 0.7145687050872052,
 0.5719635855876832,
 0.5825602864621208,
 0.6714898083897273,
 0.5280759171504354,
 0.6575505542682467,
 0.6455181557854504,
 0.5128707507064181,
 0.48109999147346505,
 0.5154225753503332,
 0.6927343657851277,
 0.7568499032726557,
 0.6217551943338058,
 0.6837548325375726,
 0.628307226242491,
 0.5600619552439654,
 0.7558024358632076,
 0.705024957420366,
 0.5950580436177932,
 0.7854467141314014,
 0.6507710586924181,
 0.6795987892503288,
 0.6789305593377529,
 0.7234606034758047,
 0.6962052689848119,
 0.5240040069178014,
 0.5747901477018047,
 0.6665973294636536,
 0.6809062927209533,
 0.4977730427182646,
 0.5032749475236964,
 0.7261703957864283,
 0.46687879703511936,
 0.5237344075163595,
 0.6597830872219502,
 0.781401446491111,
 0.6534044261797427,
 0.5812678928615301,
 0.569723960541135,
 0.787639067043673,
 0.6176164299318425,
 0.6737352246966537,
 0.7424333255687718,
 0.5259695103247677,
 0.7026361960098336,
 0.4956778284478386,
 0.6945857531535644,
 0.6326761938421818,
 0.5527201435238535,
 0.6196320186922393,
 0.5612133685434177,
 0.752921712678323,
 0.5117688717360778,
 0.5648272703139369,
 0.5606737758855918,
 0.69179292285998,
 0.6340977952389173,
 0.6703028240204054,
 0.7404709032507182,
 0.5021583610082099,
 0.5741941537941617,
 0.6728857049069967,
 0.7069553580934169,
 0.498685624286781,
 0.6104028380687972,
 0.7384965918001938,
 0.6509369497044146,
 0.6502740292878008,
 0.6382731538049161,

In [110]:
np.argmax(scores)

433

In [111]:
scores[np.argmax(scores)]

0.8457059012561223

In [112]:
X_train, X_test, y_train,y_test  = train_test_split(X,y,test_size=0.2,random_state=np.argmax(scores))
lr = LinearRegression()
pipe = make_pipeline(column_trans,lr)
pipe.fit(X_train, y_train)
y_pred  =pipe.predict(X_test)
r2_score(y_test, y_pred)

0.8457059012561223

In [113]:
import pickle

In [114]:
pickle.dump(pipe,open('LinearRegressionModel,pkl','wb'))