# Recommender Sytem :- Collaborative Filtering based , and popularity base(have formula)

In [108]:
import numpy as np
import pandas as pd

In [109]:
books = pd.read_csv('Books.csv')
users = pd.read_csv('Users.csv')
ratings = pd.read_csv('Ratings.csv')

C:\Users\USER\AppData\Local\Temp\ipykernel_7472\1748781244.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('Books.csv')

In [110]:
books.head()

         ISBN  ...                                        Image-URL-L
0  0195153448  ...  http://images.amazon.com/images/P/0195153448.0...
1  0002005018  ...  http://images.amazon.com/images/P/0002005018.0...
2  0060973129  ...  http://images.amazon.com/images/P/0060973129.0...
3  0374157065  ...  http://images.amazon.com/images/P/0374157065.0...
4  0393045218  ...  http://images.amazon.com/images/P/0393045218.0...

[5 rows x 8 columns]

In [111]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [112]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [113]:
books.shape

(271360, 8)

In [114]:
ratings.shape

(1149780, 3)

In [115]:
users.shape

(278858, 3)

In [116]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [117]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [118]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [119]:
books.duplicated().sum()

0

In [120]:
users.duplicated().sum()

0

In [121]:
ratings.duplicated().sum()

0

## Making a Popularity Base System

In [122]:
rating_with_name = ratings.merge(books,on='ISBN')

In [123]:
rating_with_name

         User-ID  ...                                        Image-URL-L
0         276725  ...  http://images.amazon.com/images/P/034545104X.0...
1         276726  ...  http://images.amazon.com/images/P/0155061224.0...
2         276727  ...  http://images.amazon.com/images/P/0446520802.0...
3         276729  ...  http://images.amazon.com/images/P/052165615X.0...
4         276729  ...  http://images.amazon.com/images/P/0521795028.0...
...          ...  ...                                                ...
1031131   276704  ...  http://images.amazon.com/images/P/0876044011.0...
1031132   276704  ...  http://images.amazon.com/images/P/1563526298.0...
1031133   276706  ...  http://images.amazon.com/images/P/0679447156.0...
1031134   276709  ...  http://images.amazon.com/images/P/0515107662.0...
1031135   276721  ...  http://images.amazon.com/images/P/0590442449.0...

[1031136 rows x 10 columns]

In [124]:
num_rating_df = rating_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()

In [125]:
num_rating_df.rename(columns={'Book-Rating':'num_ratings'},inplace=True)
num_rating_df

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [126]:
avg_rating_df = rating_with_name.groupby('Book-Title')['Book-Rating'].mean().reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg_ratings'}, inplace=True)
avg_rating_df

                                               Book-Title  avg_ratings
0        A Light in the Storm: The Civil War Diary of ...     2.250000
1                                   Always Have Popsicles     0.000000
2                    Apple Magic (The Collector's series)     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...     0.000000
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.     0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.     5.250000
241068                                Ã?Â?sterlich leben.     7.000000
241069                              Ã?Â?stlich der Berge.     2.666667
241070                                  Ã?Â?thique en toc     4.000000

[241071 rows x 2 columns]

In [127]:
popular_df = num_rating_df.merge(avg_rating_df,on='Book-Title')
popular_df

                                               Book-Title  ...  avg_ratings
0        A Light in the Storm: The Civil War Diary of ...  ...     2.250000
1                                   Always Have Popsicles  ...     0.000000
2                    Apple Magic (The Collector's series)  ...     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...  ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...  ...     0.000000
...                                                   ...  ...          ...
241066                                      Ã?Â?lpiraten.  ...     0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.  ...     5.250000
241068                                Ã?Â?sterlich leben.  ...     7.000000
241069                              Ã?Â?stlich der Berge.  ...     2.666667
241070                                  Ã?Â?thique en toc  ...     4.000000

[241071 rows x 3 columns]

In [128]:
popular_df = popular_df[popular_df['num_ratings'] >=250].sort_values('avg_ratings',ascending=False).head(50)

In [129]:
popular_df

                                               Book-Title  ...  avg_ratings
80434   Harry Potter and the Prisoner of Azkaban (Book 3)  ...     5.852804
80422        Harry Potter and the Goblet of Fire (Book 4)  ...     5.824289
80441      Harry Potter and the Sorcerer's Stone (Book 1)  ...     5.737410
80426   Harry Potter and the Order of the Phoenix (Boo...  ...     5.501441
80414    Harry Potter and the Chamber of Secrets (Book 2)  ...     5.183453
191612  The Hobbit : The Enchanting Prelude to The Lor...  ...     5.007117
187377  The Fellowship of the Ring (The Lord of the Ri...  ...     4.948370
80445   Harry Potter and the Sorcerer's Stone (Harry P...  ...     4.895652
211384     The Two Towers (The Lord of the Rings, Part 2)  ...     4.880769
219741                              To Kill a Mockingbird  ...     4.700000
183573                                  The Da Vinci Code  ...     4.642539
187880                 The Five People You Meet in Heaven  ...     4.551163
180556                             The Catcher in the Rye  ...     4.545657
196326                          The Lovely Bones: A Novel  ...     4.468726
764                                                  1984  ...     4.454225
144165                           Prodigal Summer: A Novel  ...     4.450593
128670                                         Neverwhere  ...     4.449057
206502                            The Secret Life of Bees  ...     4.447028
168719  Stupid White Men ...and Other Sorry Excuses fo...  ...     4.356890
223135  Tuesdays with Morrie: An Old Man, a Young Man,...  ...     4.354970
204387                The Red Tent (Bestselling Backlist)  ...     4.334716
191589               The Hitchhiker's Guide to the Galaxy  ...     4.328358
129379   Nickel and Dimed: On (Not) Getting By in America  ...     4.289552
93381                                       Into the Wild  ...     4.273810
63867                                      Fahrenheit 451  ...     4.264059
74750                           Girl with a Pearl Earring  ...     4.218631
136145                                          Outlander  ...     4.173145
233370  Where the Heart Is (Oprah's Book Club (Paperba...  ...     4.105983
156102                     Seabiscuit: An American Legend  ...     4.098182
107962                                         Life of Pi  ...     4.088855
176845                                     The Bean Trees  ...     4.087404
2281    A Child Called \It\": One Child's Courage to S...  ...     4.086792
8434                                       ANGELA'S ASHES  ...     4.075269
76343                                         Good in Bed  ...     4.055102
64931   Fast Food Nation: The Dark Side of the All-Ame...  ...     4.037383
12700                                       American Gods  ...     4.006623
161645                                 Skipping Christmas  ...     4.006211
105777  Left Behind: A Novel of the Earth's Last Days ...  ...     4.003145
189551    The Golden Compass (His Dark Materials, Book 1)  ...     4.000000
181679                                   The Color Purple  ...     3.964968
160336                               Silence of the Lambs  ...     3.960938
8752                                          About a Boy  ...     3.900763
158138                  Seven Up (A Stephanie Plum Novel)  ...     3.888489
175097  The Alchemist: A Fable About Following Your Dream  ...     3.875940
80069   Hard Eight : A Stephanie Plum Novel (A Stephan...  ...     3.825279
170101                       Suzanne's Diary for Nicholas  ...     3.820569
111073                                  Lord of the Flies  ...     3.818533
5664                              A Prayer for Owen Meany  ...     3.796610
212070   The Vampire Lestat (Vampire Chronicles, Book II)  ...     3.777409
233851       White Oleander : A Novel (Oprah's Book Club)  ...     3.772472

[50 rows x 3 columns]

In [154]:
print("Columns in popular_df:", popular_df.columns)

Columns in popular_df: Index(['Book-Title', 'Book-Author', 'Image-URL-M', 'num_ratings',
       'avg_ratings'],
      dtype='object')

# marge with  books for getting author or names of books

In [130]:
popular_df.merge(books,on='Book-Title')

                                            Book-Title  ...                                        Image-URL-L
0    Harry Potter and the Prisoner of Azkaban (Book 3)  ...  http://images.amazon.com/images/P/0439136350.0...
1    Harry Potter and the Prisoner of Azkaban (Book 3)  ...  http://images.amazon.com/images/P/0439136369.0...
2    Harry Potter and the Prisoner of Azkaban (Book 3)  ...  http://images.amazon.com/images/P/0786222743.0...
3         Harry Potter and the Goblet of Fire (Book 4)  ...  http://images.amazon.com/images/P/0439139597.0...
4         Harry Potter and the Goblet of Fire (Book 4)  ...  http://images.amazon.com/images/P/0439139600.0...
..                                                 ...  ...                                                ...
191                                  Lord of the Flies  ...  http://images.amazon.com/images/P/0698102193.0...
192                            A Prayer for Owen Meany  ...  http://images.amazon.com/images/P/0345361792.0...
193                            A Prayer for Owen Meany  ...  http://images.amazon.com/images/P/0345363523.0...
194   The Vampire Lestat (Vampire Chronicles, Book II)  ...  http://images.amazon.com/images/P/0345313860.0...
195       White Oleander : A Novel (Oprah's Book Club)  ...  http://images.amazon.com/images/P/0316284955.0...

[196 rows x 10 columns]

### Remove duplicated books

In [131]:
popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')

                                            Book-Title  ...                                        Image-URL-L
0    Harry Potter and the Prisoner of Azkaban (Book 3)  ...  http://images.amazon.com/images/P/0439136350.0...
3         Harry Potter and the Goblet of Fire (Book 4)  ...  http://images.amazon.com/images/P/0439139597.0...
5       Harry Potter and the Sorcerer's Stone (Book 1)  ...  http://images.amazon.com/images/P/0590353403.0...
9    Harry Potter and the Order of the Phoenix (Boo...  ...  http://images.amazon.com/images/P/043935806X.0...
13    Harry Potter and the Chamber of Secrets (Book 2)  ...  http://images.amazon.com/images/P/0439064872.0...
16   The Hobbit : The Enchanting Prelude to The Lor...  ...  http://images.amazon.com/images/P/0345339681.0...
17   The Fellowship of the Ring (The Lord of the Ri...  ...  http://images.amazon.com/images/P/0345339703.0...
26   Harry Potter and the Sorcerer's Stone (Harry P...  ...  http://images.amazon.com/images/P/059035342X.0...
28      The Two Towers (The Lord of the Rings, Part 2)  ...  http://images.amazon.com/images/P/0345339711.0...
39                               To Kill a Mockingbird  ...  http://images.amazon.com/images/P/0446310786.0...
47                                   The Da Vinci Code  ...  http://images.amazon.com/images/P/0385504209.0...
53                  The Five People You Meet in Heaven  ...  http://images.amazon.com/images/P/0786868716.0...
55                              The Catcher in the Rye  ...  http://images.amazon.com/images/P/0316769487.0...
62                           The Lovely Bones: A Novel  ...  http://images.amazon.com/images/P/0316666343.0...
63                                                1984  ...  http://images.amazon.com/images/P/0451524934.0...
72                            Prodigal Summer: A Novel  ...  http://images.amazon.com/images/P/0060959037.0...
73                                          Neverwhere  ...  http://images.amazon.com/images/P/0380789019.0...
78                             The Secret Life of Bees  ...  http://images.amazon.com/images/P/0142001740.0...
84   Stupid White Men ...and Other Sorry Excuses fo...  ...  http://images.amazon.com/images/P/0060392452.0...
85   Tuesdays with Morrie: An Old Man, a Young Man,...  ...  http://images.amazon.com/images/P/0385484518.0...
88                 The Red Tent (Bestselling Backlist)  ...  http://images.amazon.com/images/P/0312195516.0...
89                The Hitchhiker's Guide to the Galaxy  ...  http://images.amazon.com/images/P/0671461494.0...
98    Nickel and Dimed: On (Not) Getting By in America  ...  http://images.amazon.com/images/P/0805063897.0...
100                                      Into the Wild  ...  http://images.amazon.com/images/P/0385486804.0...
103                                     Fahrenheit 451  ...  http://images.amazon.com/images/P/3257208626.0...
116                          Girl with a Pearl Earring  ...  http://images.amazon.com/images/P/0452282152.0...
117                                          Outlander  ...  http://images.amazon.com/images/P/0440222915.0...
123  Where the Heart Is (Oprah's Book Club (Paperba...  ...  http://images.amazon.com/images/P/0446672211.0...
124                     Seabiscuit: An American Legend  ...  http://images.amazon.com/images/P/0449005615.0...
126                                         Life of Pi  ...  http://images.amazon.com/images/P/0151008116.0...
130                                     The Bean Trees  ...  http://images.amazon.com/images/P/0060915544.0...
133  A Child Called \It\": One Child's Courage to S...  ...  http://images.amazon.com/images/P/1558743669.0...
135                                     ANGELA'S ASHES  ...  http://images.amazon.com/images/P/0684874350.0...
137                                        Good in Bed  ...  http://images.amazon.com/images/P/0743418174.0...
139  Fast Food Nation: The Dark Side of the All-Ame...  ...  http://images.amazon.com/images/P/0060938455.0...
140                                      American Gods  ...  http://images.amazon.com/images/P/0380789035.0...
141                                 Skipping Christmas  ...  http://images.amazon.com/images/P/0385505833.0...
147  Left Behind: A Novel of the Earth's Last Days ...  ...  http://images.amazon.com/images/P/0842329129.0...
149    The Golden Compass (His Dark Materials, Book 1)  ...  http://images.amazon.com/images/P/037582345X.0...
157                                   The Color Purple  ...  http://images.amazon.com/images/P/0671617028.0...
163                               Silence of the Lambs  ...  http://images.amazon.com/images/P/0312924585.0...
166                                        About a Boy  ...  http://images.amazon.com/images/P/1573227331.0...
173                  Seven Up (A Stephanie Plum Novel)  ...  http://images.amazon.com/images/P/0312265840.0...
175  The Alchemist: A Fable About Following Your Dream  ...  http://images.amazon.com/images/P/0062502174.0...
177  Hard Eight : A Stephanie Plum Novel (A Stephan...  ...  http://images.amazon.com/images/P/0312983867.0...
182                       Suzanne's Diary for Nicholas  ...  http://images.amazon.com/images/P/0316969443.0...
186                                  Lord of the Flies  ...  http://images.amazon.com/images/P/0399501487.0...
192                            A Prayer for Owen Meany  ...  http://images.amazon.com/images/P/0345361792.0...
194   The Vampire Lestat (Vampire Chronicles, Book II)  ...  http://images.amazon.com/images/P/0345313860.0...
195       White Oleander : A Novel (Oprah's Book Club)  ...  http://images.amazon.com/images/P/0316284955.0...

[50 rows x 10 columns]

In [132]:
popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')

                                            Book-Title  ...                                        Image-URL-L
0    Harry Potter and the Prisoner of Azkaban (Book 3)  ...  http://images.amazon.com/images/P/0439136350.0...
3         Harry Potter and the Goblet of Fire (Book 4)  ...  http://images.amazon.com/images/P/0439139597.0...
5       Harry Potter and the Sorcerer's Stone (Book 1)  ...  http://images.amazon.com/images/P/0590353403.0...
9    Harry Potter and the Order of the Phoenix (Boo...  ...  http://images.amazon.com/images/P/043935806X.0...
13    Harry Potter and the Chamber of Secrets (Book 2)  ...  http://images.amazon.com/images/P/0439064872.0...
16   The Hobbit : The Enchanting Prelude to The Lor...  ...  http://images.amazon.com/images/P/0345339681.0...
17   The Fellowship of the Ring (The Lord of the Ri...  ...  http://images.amazon.com/images/P/0345339703.0...
26   Harry Potter and the Sorcerer's Stone (Harry P...  ...  http://images.amazon.com/images/P/059035342X.0...
28      The Two Towers (The Lord of the Rings, Part 2)  ...  http://images.amazon.com/images/P/0345339711.0...
39                               To Kill a Mockingbird  ...  http://images.amazon.com/images/P/0446310786.0...
47                                   The Da Vinci Code  ...  http://images.amazon.com/images/P/0385504209.0...
53                  The Five People You Meet in Heaven  ...  http://images.amazon.com/images/P/0786868716.0...
55                              The Catcher in the Rye  ...  http://images.amazon.com/images/P/0316769487.0...
62                           The Lovely Bones: A Novel  ...  http://images.amazon.com/images/P/0316666343.0...
63                                                1984  ...  http://images.amazon.com/images/P/0451524934.0...
72                            Prodigal Summer: A Novel  ...  http://images.amazon.com/images/P/0060959037.0...
73                                          Neverwhere  ...  http://images.amazon.com/images/P/0380789019.0...
78                             The Secret Life of Bees  ...  http://images.amazon.com/images/P/0142001740.0...
84   Stupid White Men ...and Other Sorry Excuses fo...  ...  http://images.amazon.com/images/P/0060392452.0...
85   Tuesdays with Morrie: An Old Man, a Young Man,...  ...  http://images.amazon.com/images/P/0385484518.0...
88                 The Red Tent (Bestselling Backlist)  ...  http://images.amazon.com/images/P/0312195516.0...
89                The Hitchhiker's Guide to the Galaxy  ...  http://images.amazon.com/images/P/0671461494.0...
98    Nickel and Dimed: On (Not) Getting By in America  ...  http://images.amazon.com/images/P/0805063897.0...
100                                      Into the Wild  ...  http://images.amazon.com/images/P/0385486804.0...
103                                     Fahrenheit 451  ...  http://images.amazon.com/images/P/3257208626.0...
116                          Girl with a Pearl Earring  ...  http://images.amazon.com/images/P/0452282152.0...
117                                          Outlander  ...  http://images.amazon.com/images/P/0440222915.0...
123  Where the Heart Is (Oprah's Book Club (Paperba...  ...  http://images.amazon.com/images/P/0446672211.0...
124                     Seabiscuit: An American Legend  ...  http://images.amazon.com/images/P/0449005615.0...
126                                         Life of Pi  ...  http://images.amazon.com/images/P/0151008116.0...
130                                     The Bean Trees  ...  http://images.amazon.com/images/P/0060915544.0...
133  A Child Called \It\": One Child's Courage to S...  ...  http://images.amazon.com/images/P/1558743669.0...
135                                     ANGELA'S ASHES  ...  http://images.amazon.com/images/P/0684874350.0...
137                                        Good in Bed  ...  http://images.amazon.com/images/P/0743418174.0...
139  Fast Food Nation: The Dark Side of the All-Ame...  ...  http://images.amazon.com/images/P/0060938455.0...
140                                      American Gods  ...  http://images.amazon.com/images/P/0380789035.0...
141                                 Skipping Christmas  ...  http://images.amazon.com/images/P/0385505833.0...
147  Left Behind: A Novel of the Earth's Last Days ...  ...  http://images.amazon.com/images/P/0842329129.0...
149    The Golden Compass (His Dark Materials, Book 1)  ...  http://images.amazon.com/images/P/037582345X.0...
157                                   The Color Purple  ...  http://images.amazon.com/images/P/0671617028.0...
163                               Silence of the Lambs  ...  http://images.amazon.com/images/P/0312924585.0...
166                                        About a Boy  ...  http://images.amazon.com/images/P/1573227331.0...
173                  Seven Up (A Stephanie Plum Novel)  ...  http://images.amazon.com/images/P/0312265840.0...
175  The Alchemist: A Fable About Following Your Dream  ...  http://images.amazon.com/images/P/0062502174.0...
177  Hard Eight : A Stephanie Plum Novel (A Stephan...  ...  http://images.amazon.com/images/P/0312983867.0...
182                       Suzanne's Diary for Nicholas  ...  http://images.amazon.com/images/P/0316969443.0...
186                                  Lord of the Flies  ...  http://images.amazon.com/images/P/0399501487.0...
192                            A Prayer for Owen Meany  ...  http://images.amazon.com/images/P/0345361792.0...
194   The Vampire Lestat (Vampire Chronicles, Book II)  ...  http://images.amazon.com/images/P/0345313860.0...
195       White Oleander : A Novel (Oprah's Book Club)  ...  http://images.amazon.com/images/P/0316284955.0...

[50 rows x 10 columns]

In [133]:
print(type(books))

<class 'pandas.core.frame.DataFrame'>

In [134]:
popular_df = popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-M','num_ratings','avg_ratings']]

In [135]:
popular_df

                                            Book-Title  ... avg_ratings
0    Harry Potter and the Prisoner of Azkaban (Book 3)  ...    5.852804
3         Harry Potter and the Goblet of Fire (Book 4)  ...    5.824289
5       Harry Potter and the Sorcerer's Stone (Book 1)  ...    5.737410
9    Harry Potter and the Order of the Phoenix (Boo...  ...    5.501441
13    Harry Potter and the Chamber of Secrets (Book 2)  ...    5.183453
16   The Hobbit : The Enchanting Prelude to The Lor...  ...    5.007117
17   The Fellowship of the Ring (The Lord of the Ri...  ...    4.948370
26   Harry Potter and the Sorcerer's Stone (Harry P...  ...    4.895652
28      The Two Towers (The Lord of the Rings, Part 2)  ...    4.880769
39                               To Kill a Mockingbird  ...    4.700000
47                                   The Da Vinci Code  ...    4.642539
53                  The Five People You Meet in Heaven  ...    4.551163
55                              The Catcher in the Rye  ...    4.545657
62                           The Lovely Bones: A Novel  ...    4.468726
63                                                1984  ...    4.454225
72                            Prodigal Summer: A Novel  ...    4.450593
73                                          Neverwhere  ...    4.449057
78                             The Secret Life of Bees  ...    4.447028
84   Stupid White Men ...and Other Sorry Excuses fo...  ...    4.356890
85   Tuesdays with Morrie: An Old Man, a Young Man,...  ...    4.354970
88                 The Red Tent (Bestselling Backlist)  ...    4.334716
89                The Hitchhiker's Guide to the Galaxy  ...    4.328358
98    Nickel and Dimed: On (Not) Getting By in America  ...    4.289552
100                                      Into the Wild  ...    4.273810
103                                     Fahrenheit 451  ...    4.264059
116                          Girl with a Pearl Earring  ...    4.218631
117                                          Outlander  ...    4.173145
123  Where the Heart Is (Oprah's Book Club (Paperba...  ...    4.105983
124                     Seabiscuit: An American Legend  ...    4.098182
126                                         Life of Pi  ...    4.088855
130                                     The Bean Trees  ...    4.087404
133  A Child Called \It\": One Child's Courage to S...  ...    4.086792
135                                     ANGELA'S ASHES  ...    4.075269
137                                        Good in Bed  ...    4.055102
139  Fast Food Nation: The Dark Side of the All-Ame...  ...    4.037383
140                                      American Gods  ...    4.006623
141                                 Skipping Christmas  ...    4.006211
147  Left Behind: A Novel of the Earth's Last Days ...  ...    4.003145
149    The Golden Compass (His Dark Materials, Book 1)  ...    4.000000
157                                   The Color Purple  ...    3.964968
163                               Silence of the Lambs  ...    3.960938
166                                        About a Boy  ...    3.900763
173                  Seven Up (A Stephanie Plum Novel)  ...    3.888489
175  The Alchemist: A Fable About Following Your Dream  ...    3.875940
177  Hard Eight : A Stephanie Plum Novel (A Stephan...  ...    3.825279
182                       Suzanne's Diary for Nicholas  ...    3.820569
186                                  Lord of the Flies  ...    3.818533
192                            A Prayer for Owen Meany  ...    3.796610
194   The Vampire Lestat (Vampire Chronicles, Book II)  ...    3.777409
195       White Oleander : A Novel (Oprah's Book Club)  ...    3.772472

[50 rows x 5 columns]

# collaborative Filtering Based Recommender System

In [136]:
rating_with_name

         User-ID  ...                                        Image-URL-L
0         276725  ...  http://images.amazon.com/images/P/034545104X.0...
1         276726  ...  http://images.amazon.com/images/P/0155061224.0...
2         276727  ...  http://images.amazon.com/images/P/0446520802.0...
3         276729  ...  http://images.amazon.com/images/P/052165615X.0...
4         276729  ...  http://images.amazon.com/images/P/0521795028.0...
...          ...  ...                                                ...
1031131   276704  ...  http://images.amazon.com/images/P/0876044011.0...
1031132   276704  ...  http://images.amazon.com/images/P/1563526298.0...
1031133   276706  ...  http://images.amazon.com/images/P/0679447156.0...
1031134   276709  ...  http://images.amazon.com/images/P/0515107662.0...
1031135   276721  ...  http://images.amazon.com/images/P/0590442449.0...

[1031136 rows x 10 columns]

In [137]:
x = rating_with_name.groupby('User-ID').count()['Book-Rating'] >200
padhe_likhe_users = x[x].index

In [138]:
rating_with_name[rating_with_name['User-ID'].isin(padhe_likhe_users)]

         User-ID  ...                                        Image-URL-L
1150      277427  ...  http://images.amazon.com/images/P/002542730X.0...
1151      277427  ...  http://images.amazon.com/images/P/0026217457.0...
1152      277427  ...  http://images.amazon.com/images/P/003008685X.0...
1153      277427  ...  http://images.amazon.com/images/P/0030615321.0...
1154      277427  ...  http://images.amazon.com/images/P/0060002050.0...
...          ...  ...                                                ...
1029357   275970  ...  http://images.amazon.com/images/P/1931868123.0...
1029358   275970  ...  http://images.amazon.com/images/P/3411086211.0...
1029359   275970  ...  http://images.amazon.com/images/P/3829021860.0...
1029360   275970  ...  http://images.amazon.com/images/P/4770019572.0...
1029361   275970  ...  http://images.amazon.com/images/P/9626340762.0...

[474007 rows x 10 columns]

In [139]:
filtered_rating = rating_with_name[rating_with_name['User-ID'].isin(padhe_likhe_users)]

In [140]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating'] >= 50
famous_books =y[y].index

In [141]:
final_rating = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [142]:
final_rating

         User-ID  ...                                        Image-URL-L
1150      277427  ...  http://images.amazon.com/images/P/002542730X.0...
1163      277427  ...  http://images.amazon.com/images/P/0060930535.0...
1165      277427  ...  http://images.amazon.com/images/P/0060934417.0...
1168      277427  ...  http://images.amazon.com/images/P/0061009059.0...
1174      277427  ...  http://images.amazon.com/images/P/006440188X.0...
...          ...  ...                                                ...
1029196   275970  ...  http://images.amazon.com/images/P/1400031354.0...
1029197   275970  ...  http://images.amazon.com/images/P/1400031362.0...
1029270   275970  ...  http://images.amazon.com/images/P/1573229725.0...
1029309   275970  ...  http://images.amazon.com/images/P/1586210661.0...
1029310   275970  ...  http://images.amazon.com/images/P/1586212230.0...

[58586 rows x 10 columns]

In [143]:
pt = final_rating.pivot_table(index='Book-Title',columns='User-ID', values='Book-Rating')

In [144]:
pt

User-ID                                             254     ...  278418
Book-Title                                                  ...
1984                                                   9.0  ...     NaN
1st to Die: A Novel                                    NaN  ...     NaN
2nd Chance                                             NaN  ...     NaN
4 Blondes                                              NaN  ...     NaN
A Bend in the Road                                     0.0  ...     NaN
...                                                    ...  ...     ...
Year of Wonders                                        NaN  ...     NaN
You Belong To Me                                       NaN  ...     NaN
Zen and the Art of Motorcycle Maintenance: An I...     NaN  ...     NaN
Zoya                                                   NaN  ...     NaN
\O\" Is for Outlaw"                                    NaN  ...     NaN

[706 rows x 810 columns]

In [145]:
pt.fillna(0,inplace=True)

In [146]:
pt

User-ID                                             254     ...  278418
Book-Title                                                  ...
1984                                                   9.0  ...     0.0
1st to Die: A Novel                                    0.0  ...     0.0
2nd Chance                                             0.0  ...     0.0
4 Blondes                                              0.0  ...     0.0
A Bend in the Road                                     0.0  ...     0.0
...                                                    ...  ...     ...
Year of Wonders                                        0.0  ...     0.0
You Belong To Me                                       0.0  ...     0.0
Zen and the Art of Motorcycle Maintenance: An I...     0.0  ...     0.0
Zoya                                                   0.0  ...     0.0
\O\" Is for Outlaw"                                    0.0  ...     0.0

[706 rows x 810 columns]

In [147]:
from sklearn.metrics.pairwise import cosine_similarity

In [148]:
similarity_score = cosine_similarity(pt)

In [149]:
def recommend(book_name):
    # index fetch
    index = np.where(pt.index==book_name)[0][0]
    simialar_items = sorted(list(enumerate(similarity_score[index])),key=lambda x:x[1],reverse=True)[1:6]

    for i in simialar_items:
        print(pt.index[i[0]])

In [150]:
recommend('Message in a Bottle')

Nights in Rodanthe
The Mulberry Tree
A Walk to Remember
River's End
Nightmares &amp; Dreamscapes

In [151]:
import pickle
pickle.dump(popular_df,open('popular.pkl','wb'))

In [152]:
print(popular_df.columns)

Index(['Book-Title', 'Book-Author', 'Image-URL-M', 'num_ratings',
       'avg_ratings'],
      dtype='object')

In [153]:

pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(similarity_score,open('similarity_scores.pkl','wb'))