In [1]:
import numpy as np
import pandas as pd
import os

In [3]:
df = pd.read_csv('IMDB Dataset.csv')
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
# One review
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

## Text Cleaning 

* 1. Sample 10000 rows
* 2. Remove htm; tags
* 3. Remove special charaters
* 4. Converting every thing to lower case
* 5. Removing Stop words
* 6. Stemming

In [5]:
df= df.sample(10000)

In [6]:
df.shape

(10000, 2)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 10859 to 4880
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 234.4+ KB

In [8]:
df['sentiment'].replace({'positive':1,'negative':0}, inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_12612\2768535601.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sentiment'].replace({'positive':1,'negative':0}, inplace=True)

In [9]:
df.head()

                                                  review  sentiment
10859  It was poorly shot. Looks Like a rush job, las...          0
43326  There are movies, and there are films. Movies ...          1
36954  If you're a fan of the late Gram Parsons then ...          0
28056  I was utterly disappointed by this movie. I ha...          0
24921  This movie must have looked when it was being ...          0

In [10]:
import re 
clean = re.compile('<.*?>')
re.sub(clean, '' ,df.iloc[2].review)

'If you\'re a fan of the late Gram Parsons then this movie is definitely going to divide you! Part comedy, part road movie, but mostly a bad fictionalization of one of rock history\'s oddest tales.SPOILERS-- Basically the story concerns a well-known roadie named Phil Kaufman (played by Johnny Knoxville) who "supposedly" made a pact with cult rock/country/folk music hero Gram Parsons that stated when one of them died first (it didn\'t matter which one it was) that the other living one was to take the deceased out to the desert, Joshua Tree National Park in California to be exact, and set the body ablaze...so as to free the spirit and become one with the earth, and so on! Sure to keep his word the barely sober Kaufman, with the assistance of a self-hating, pot-headed buddy, jacks the body of the late Parsons -whom had fatally overdosed from a drug and booze bender a day prior- from the airport. And shortly after that what ensues is a cringe-worthy combination of fiction and truth where the late Parsons girlfriend, Kaufman\'s girlfriend, Parsons stone-faced father, and a gaggle of police officers and other pointless idiotic characters all try to beat the clock (so to speak) in trying to catch Kaufman and his pal before they get the chance to torch Parsons body! The film\'s incompetent direction, bad acting, and lame offbeat tone in general all sink this movie faster than the Titanic. And not to mention the huge fact that this movie is not even halfway telling the truth of the actual events that took place. The accuracies that should have replaced the inaccuracies, as far as I\'ve heard them, include: number 1., Parsons was married at the time of his death and even had a child, so what the hell was that all about with the girlfriend\'s and the chasing and whatnot?, number 2., Kaufman\'s drugged-out buddy was a known willing participant (unlike what the movie attempts to portray) in the disposing of Parson\'s body, and finally number 3., Gram Parsons real-life father died when he was just a boy, and so it was Parson\'s step-father (who could have honestly cared less about Gram Parsons when he was still alive) in real-life that took care of the body after it was torched! Altogether though, what probably disturbs me the most about this movie is that the real Phil Kaufman was actually on set to help assist with the facts of the story. And yet still, the movie ended up becoming so untrue and so bad that it really boggles my mind, frankly! Also as the mediocre aforementioned acting in the film is concerned it\'s lead character, played by the ultra-grating Johnny Knoxville (Phil Kaufman), is not only a bad actor but it actually seems as if he were asleep throughout most of the movie, and the rest of the pathetic cast are for the most part either hysterical, brain-dead, or seem utterly clueless as to what they\'re actually doing there in the first place! Overall, if you like Johnny Knoxville and or really dig the so-bad-they\'re-not-even-good buddy flicks then I suppose you just might get a kick out of this movie! But, if you\'re like me and are a fan of the late Gram Parsons, enjoy films that attempt to tell the truth as much as they can especially if they\'re based on an actual real-life story, and or you just like good films, be-them road movies, or fictional slice-of-life stuff, you will truly loathe this film and advise others to do likewise. I obviously hated this movie and wished it had never been made in the first place, but since it was made I would have preferred it to have turned out differently than what it did, unfortunately! Maybe some day the real facts of the story will come through and be made into a really great biopic on all of Gram Parsons life...not just what happened to his body after his spirit left it. But, until that time comes all we as an audience, and or fans of the late performer get is this sad waste of film and an all-around terrible memorial (of sorts) to the musical legacy that Gram Parsons was known to have left behind. It should also be noted that they did actually use Parsons music, and a few others as well in the flick, but not surprisingly though, you never get to hear enough of it to really enjoy it even in the slightest bit. (Turkey-Zero Stars)'

In [11]:
# Function to clean html tags
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean,'',text)

In [12]:
df['review'] = df['review'].apply(clean_html)

In [13]:
# converting everything to lowet

def convert_lower(text):
    return text.lower()

In [14]:
df['review']  =df['review'].apply(convert_lower)

In [15]:
# function to remove special characters
def remove_special(text):
    x=''

    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x+ ' '
    return x

In [16]:
df['review'] = df['review'].apply(remove_special)

In [17]:
# Remove the stop words
import nltk

In [18]:
from nltk.corpus import stopwords

In [19]:
df

                                                  review  sentiment
10859  it was poorly shot  looks like a rush job  las...          0
43326  there are movies  and there are films  movies ...          1
36954  if you re a fan of the late gram parsons then ...          0
28056  i was utterly disappointed by this movie  i ha...          0
24921  this movie must have looked when it was being ...          0
...                                                  ...        ...
21838  honestly  if anyone has a brain  there s not 1...          0
41771  note  i couldn t force myself to actually writ...          0
955    previous reviewer claudio carvalho gave a much...          1
2425   in cold blood has to be ranked as first rate m...          1
4880   a friend of mine loves tacky horror films so i...          0

[10000 rows x 2 columns]

In [20]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [21]:
def remove_stopwords(text):
    x =[]
    for i in text.split():
        
        if i not in stopwords.words('english'):
            x.append(i)
    y = x[:]
    x.clear()
    return y

In [22]:
df['review'] = df['review'].apply(remove_stopwords)

In [23]:
df

                                                  review  sentiment
10859  [poorly, shot, looks, like, rush, job, last, m...          0
43326  [movies, films, movies, often, merely, cinemat...          1
36954  [fan, late, gram, parsons, movie, definitely, ...          0
28056  [utterly, disappointed, movie, read, reviews, ...          0
24921  [movie, must, looked, pitched, development, st...          0
...                                                  ...        ...
21838  [honestly, anyone, brain, 1, positive, thingto...          0
41771  [note, force, actually, write, constructive, r...          0
955    [previous, reviewer, claudio, carvalho, gave, ...          1
2425   [cold, blood, ranked, first, rate, movie, maki...          1
4880   [friend, mine, loves, tacky, horror, films, of...          0

[10000 rows x 2 columns]