In [5]:
import numpy as np
import pandas as pd
import os

In [6]:
df = pd.read_csv('IMDB Dataset.csv')
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [7]:
# One review
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

## Text Cleaning 

* 1. Sample 10000 rows
* 2. Remove htm; tags
* 3. Remove special charaters
* 4. Converting every thing to lower case
* 5. Removing Stop words
* 6. Stemming

In [8]:
df= df.sample(10000)

In [9]:
df.shape

(10000, 2)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 9732 to 27546
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 234.4+ KB

In [11]:
df['sentiment'].replace({'positive':1,'negative':0}, inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_2712\2768535601.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sentiment'].replace({'positive':1,'negative':0}, inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_2712\2768535601.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sentiment'].replace({'positive':1,'negative':0}, inplace=True)

In [12]:
df.head()

                                                  review  sentiment
9732   This is a complex film that explores the effec...          1
23573  Normally, movies stay out of the realm of "dom...          1
13652  This is the worst hindi film I have ever seen....          0
1114   As a fan of Henriksen (I liked him in the "Mil...          0
48748  THE NIGHT EVELYN CAME OUT OF THE GRAVE (Emilio...          0

In [13]:
import re 
clean = re.compile('<.*?>')
re.sub(clean, '' ,df.iloc[2].review)

'This is the worst hindi film I have ever seen. It conforms to all the stereotypes of bad Hindi films. The plot is ridiculous, the acting over the top, and Shah Rukh manages to fit in a couple of song sequences even though he is playing the character of a dumb man.'

In [14]:
# Function to clean html tags
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean,'',text)

In [15]:
df['review'] = df['review'].apply(clean_html)

In [16]:
# converting everything to lowet

def convert_lower(text):
    return text.lower()

In [17]:
df['review']  =df['review'].apply(convert_lower)

In [18]:
# function to remove special characters
def remove_special(text):
    x=''

    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x+ ' '
    return x

In [19]:
df['review'] = df['review'].apply(remove_special)

In [20]:
# Remove the stop words
import nltk

In [21]:
from nltk.corpus import stopwords

In [22]:
df

                                                  review  sentiment
9732   this is a complex film that explores the effec...          1
23573  normally  movies stay out of the realm of  dom...          1
13652  this is the worst hindi film i have ever seen ...          0
1114   as a fan of henriksen  i liked him in the  mil...          0
48748  the night evelyn came out of the grave  emilio...          0
...                                                  ...        ...
2967   this is like a school video project and a prop...          0
18273  i love pop culture  but i was a little apprehe...          1
31344  i m one of those people who usually watch prog...          1
11857  this movie was filmed in my hometown and i was...          0
27546  it s taken years for cult icon bruce campbell ...          1

[10000 rows x 2 columns]

In [23]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [24]:
def remove_stopwords(text):
    x =[]
    for i in text.split():
        
        if i not in stopwords.words('english'):
            x.append(i)
    y = x[:]
    x.clear()
    return y

In [25]:
df['review'] = df['review'].apply(remove_stopwords)

In [26]:
df

                                                  review  sentiment
9732   [complex, film, explores, effects, fordist, ta...          1
23573  [normally, movies, stay, realm, domestic, dram...          1
13652  [worst, hindi, film, ever, seen, conforms, ste...          0
1114   [fan, henriksen, liked, millennium, series, co...          0
48748  [night, evelyn, came, grave, emilio, miraglia,...          0
...                                                  ...        ...
2967   [like, school, video, project, propaganda, fil...          0
18273  [love, pop, culture, little, apprehensive, fir...          1
31344  [one, people, usually, watch, programs, keep, ...          1
11857  [movie, filmed, hometown, acquainted, many, ac...          0
27546  [taken, years, cult, icon, bruce, campbell, ge...          1

[10000 rows x 2 columns]

In [27]:
# Perform stemming 
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [28]:
y=[]
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    Z =y[:]
    y.clear()
    return Z

In [29]:
stem_words(['I','loved','loving','it'])

['i', 'love', 'love', 'it']

In [30]:
df['review'] = df['review'].apply(stem_words)